<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Cobytelabs.Modulus.AspNetCore" Version="1.3.0" />
    <PackageReference Include="Cobytelabs.Modulus.Authorization.Management" Version="1.3.0" />
    <PackageReference Include="Cobytelabs.Modulus.Core" Version="1.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TradeFlow.Shared.Application\TradeFlow.Shared.Application.csproj" />
  </ItemGroup>

</Project>
