// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProcureFlow.Modules.TradeFinance.Infrastructure.Database;

#nullable disable

namespace ProcureFlow.Modules.TradeFinance.Infrastructure.Migrations
{
    [DbContext(typeof(TradeFinanceDbContext))]
    [Migration("20260819054815_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("tradefin")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Modulus.Outbox.Abstractions.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CausationId")
                        .HasColumnType("text")
                        .HasColumnName("causation_id");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("text")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("LockedBy")
                        .HasColumnType("text")
                        .HasColumnName("locked_by");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("message_type");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("module_name");

                    b.Property<DateTime?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_outbox_messages_tenant_id");

                    b.HasIndex("ProcessedAt", "CreatedAt")
                        .HasDatabaseName("ix_outbox_messages_processed_at_created_at");

                    b.HasIndex("ProcessedAt", "LockedUntil", "RetryCount")
                        .HasDatabaseName("ix_outbox_messages_processed_at_locked_until_retry_count");

                    b.ToTable("outbox_messages", "tradefin");
                });

            modelBuilder.Entity("ProcureFlow.Modules.TradeFinance.Domain.Entities.BankFacility", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BankId")
                        .HasColumnType("uuid")
                        .HasColumnName("bank_id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<decimal>("LimitAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("limit_amount");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_bank_facilities");

                    b.HasIndex("TenantId", "BankId")
                        .IsUnique()
                        .HasDatabaseName("ix_bank_facilities_tenant_id_bank_id");

                    b.ToTable("bank_facilities", "tradefin");
                });

            modelBuilder.Entity("ProcureFlow.Modules.TradeFinance.Domain.Entities.LetterOfCredit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount");

                    b.Property<Guid>("ApplicantCompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("applicant_company_id");

                    b.Property<string>("BeneficiaryName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("beneficiary_name");

                    b.Property<Guid>("BeneficiaryVendorId")
                        .HasColumnType("uuid")
                        .HasColumnName("beneficiary_vendor_id");

                    b.Property<decimal>("BookingFxRate")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("booking_fx_rate");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cancellation_reason");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<DateOnly>("ExpiryDate")
                        .HasColumnType("date")
                        .HasColumnName("expiry_date");

                    b.Property<Guid?>("FileId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_id");

                    b.Property<string>("Incoterm")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("incoterm");

                    b.Property<Guid>("IssuingBankId")
                        .HasColumnType("uuid")
                        .HasColumnName("issuing_bank_id");

                    b.Property<DateOnly>("LatestShipmentDate")
                        .HasColumnType("date")
                        .HasColumnName("latest_shipment_date");

                    b.Property<string>("LcNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("lc_number");

                    b.Property<decimal>("MarginPct")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("margin_pct");

                    b.Property<bool>("PartialShipmentAllowed")
                        .HasColumnType("boolean")
                        .HasColumnName("partial_shipment_allowed");

                    b.Property<Guid?>("PoId")
                        .HasColumnType("uuid")
                        .HasColumnName("po_id");

                    b.Property<string>("PortOfDischarge")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("port_of_discharge");

                    b.Property<string>("PortOfLoading")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("port_of_loading");

                    b.Property<decimal?>("RealizedFxRate")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("realized_fx_rate");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("TolerancePct")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("tolerance_pct");

                    b.Property<bool>("TransshipmentAllowed")
                        .HasColumnType("boolean")
                        .HasColumnName("transshipment_allowed");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_letters_of_credit");

                    b.HasIndex("TenantId", "LcNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_letters_of_credit_tenant_id_lc_number");

                    b.ToTable("letters_of_credit", "tradefin");
                });

            modelBuilder.Entity("ProcureFlow.Modules.TradeFinance.Domain.Entities.PaymentObligation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<bool>("NotifiedT3")
                        .HasColumnType("boolean")
                        .HasColumnName("notified_t3");

                    b.Property<bool>("NotifiedT7")
                        .HasColumnType("boolean")
                        .HasColumnName("notified_t7");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source_number");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_payment_obligations");

                    b.HasIndex("TenantId", "DueDate", "Status")
                        .HasDatabaseName("ix_payment_obligations_tenant_id_due_date_status");

                    b.ToTable("payment_obligations", "tradefin");
                });

            modelBuilder.Entity("ProcureFlow.Modules.TradeFinance.Domain.Entities.SwiftMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentRef")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("content_ref");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("direction");

                    b.Property<Guid?>("LinkedLcId")
                        .HasColumnType("uuid")
                        .HasColumnName("linked_lc_id");

                    b.Property<Guid?>("LinkedTtId")
                        .HasColumnType("uuid")
                        .HasColumnName("linked_tt_id");

                    b.Property<string>("MtType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("mt_type");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reference");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_swift_messages");

                    b.HasIndex("TenantId", "Reference")
                        .IsUnique()
                        .HasDatabaseName("ix_swift_messages_tenant_id_reference");

                    b.ToTable("swift_messages", "tradefin");
                });

            modelBuilder.Entity("ProcureFlow.Modules.TradeFinance.Domain.Entities.TtPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount");

                    b.Property<string>("BankRef")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("bank_ref");

                    b.Property<string>("BeneficiaryName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("beneficiary_name");

                    b.Property<decimal?>("Charges")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("charges");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<Guid?>("FileId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_id");

                    b.Property<decimal?>("FxRate")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("fx_rate");

                    b.Property<Guid?>("PoId")
                        .HasColumnType("uuid")
                        .HasColumnName("po_id");

                    b.Property<int>("ScheduleType")
                        .HasColumnType("integer")
                        .HasColumnName("schedule_type");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TtNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tt_number");

                    b.Property<DateOnly?>("ValueDate")
                        .HasColumnType("date")
                        .HasColumnName("value_date");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid")
                        .HasColumnName("vendor_id");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_tt_payments");

                    b.HasIndex("TenantId", "TtNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_tt_payments_tenant_id_tt_number");

                    b.ToTable("tt_payments", "tradefin");
                });

            modelBuilder.Entity("ProcureFlow.Modules.TradeFinance.Domain.Entities.BankFacility", b =>
                {
                    b.OwnsMany("ProcureFlow.Modules.TradeFinance.Domain.Entities.FacilityExposureEntry", "Entries", b1 =>
                        {
                            b1.Property<Guid>("FacilityId")
                                .HasColumnType("uuid")
                                .HasColumnName("facility_id");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("amount");

                            b1.Property<DateOnly>("BookedOn")
                                .HasColumnType("date")
                                .HasColumnName("booked_on");

                            b1.Property<string>("Reason")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("reason");

                            b1.Property<Guid>("ReferenceId")
                                .HasColumnType("uuid")
                                .HasColumnName("reference_id");

                            b1.Property<string>("ReferenceNumber")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("reference_number");

                            b1.HasKey("FacilityId", "Id")
                                .HasName("pk_facility_exposure_entries");

                            b1.ToTable("facility_exposure_entries", "tradefin");

                            b1.WithOwner()
                                .HasForeignKey("FacilityId")
                                .HasConstraintName("fk_facility_exposure_entries_bank_facilities_facility_id");
                        });

                    b.Navigation("Entries");
                });

            modelBuilder.Entity("ProcureFlow.Modules.TradeFinance.Domain.Entities.LetterOfCredit", b =>
                {
                    b.OwnsMany("ProcureFlow.Modules.TradeFinance.Domain.Entities.LcAmendment", "Amendments", b1 =>
                        {
                            b1.Property<Guid>("LcId")
                                .HasColumnType("uuid")
                                .HasColumnName("lc_id");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<bool>("Approved")
                                .HasColumnType("boolean")
                                .HasColumnName("approved");

                            b1.Property<string>("ApprovedBy")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("approved_by");

                            b1.Property<int>("Doa")
                                .HasColumnType("integer")
                                .HasColumnName("doa");

                            b1.Property<string>("Reason")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("reason");

                            b1.Property<string>("ReasonCode")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("reason_code");

                            b1.Property<string>("RequestedBy")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("requested_by");

                            b1.Property<bool>("TenorIncreasing")
                                .HasColumnType("boolean")
                                .HasColumnName("tenor_increasing");

                            b1.Property<decimal?>("ValueDelta")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("value_delta");

                            b1.Property<int>("Version")
                                .HasColumnType("integer")
                                .HasColumnName("version");

                            b1.HasKey("LcId", "Id")
                                .HasName("pk_lc_amendments");

                            b1.ToTable("lc_amendments", "tradefin");

                            b1.WithOwner()
                                .HasForeignKey("LcId")
                                .HasConstraintName("fk_lc_amendments_letters_of_credit_lc_id");
                        });

                    b.OwnsMany("ProcureFlow.Modules.TradeFinance.Domain.Entities.LcCharge", "Charges", b1 =>
                        {
                            b1.Property<Guid>("LcId")
                                .HasColumnType("uuid")
                                .HasColumnName("lc_id");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("amount");

                            b1.Property<DateTime>("AtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("at_utc");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("currency");

                            b1.Property<string>("RefDoc")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("ref_doc");

                            b1.Property<int>("Type")
                                .HasColumnType("integer")
                                .HasColumnName("type");

                            b1.HasKey("LcId", "Id")
                                .HasName("pk_lc_charges");

                            b1.ToTable("lc_charges", "tradefin");

                            b1.WithOwner()
                                .HasForeignKey("LcId")
                                .HasConstraintName("fk_lc_charges_letters_of_credit_lc_id");
                        });

                    b.OwnsMany("ProcureFlow.Modules.TradeFinance.Domain.Entities.LcPresentation", "Presentations", b1 =>
                        {
                            b1.Property<Guid>("LcId")
                                .HasColumnType("uuid")
                                .HasColumnName("lc_id");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.PrimitiveCollection<string[]>("DocumentRefs")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("text[]")
                                .HasColumnName("document_refs");

                            b1.Property<string>("PresentationNo")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("presentation_no");

                            b1.Property<DateTime>("PresentedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("presented_at_utc");

                            b1.Property<int>("Status")
                                .HasColumnType("integer")
                                .HasColumnName("status");

                            b1.HasKey("LcId", "Id")
                                .HasName("pk_lc_presentations");

                            b1.ToTable("lc_presentations", "tradefin");

                            b1.WithOwner()
                                .HasForeignKey("LcId")
                                .HasConstraintName("fk_lc_presentations_letters_of_credit_lc_id");

                            b1.OwnsMany("ProcureFlow.Modules.TradeFinance.Domain.Entities.LcDiscrepancy", "Discrepancies", b2 =>
                                {
                                    b2.Property<Guid>("LcId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("lc_id");

                                    b2.Property<Guid>("PresentationId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("presentation_id");

                                    b2.Property<Guid>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<string>("Code")
                                        .IsRequired()
                                        .HasMaxLength(20)
                                        .HasColumnType("character varying(20)")
                                        .HasColumnName("code");

                                    b2.Property<string>("Description")
                                        .IsRequired()
                                        .HasMaxLength(500)
                                        .HasColumnType("character varying(500)")
                                        .HasColumnName("description");

                                    b2.HasKey("LcId", "PresentationId", "Id")
                                        .HasName("pk_lc_presentation_discrepancies");

                                    b2.ToTable("lc_presentation_discrepancies", "tradefin");

                                    b2.WithOwner()
                                        .HasForeignKey("LcId", "PresentationId")
                                        .HasConstraintName("fk_lc_presentation_discrepancies_lc_presentations_lc_id_presen");
                                });

                            b1.Navigation("Discrepancies");
                        });

                    b.OwnsMany("ProcureFlow.Modules.TradeFinance.Domain.Entities.MarginLedgerEntry", "MarginLedger", b1 =>
                        {
                            b1.Property<Guid>("LcId")
                                .HasColumnType("uuid")
                                .HasColumnName("lc_id");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("amount");

                            b1.Property<Guid>("BankId")
                                .HasColumnType("uuid")
                                .HasColumnName("bank_id");

                            b1.Property<DateOnly>("BookedOn")
                                .HasColumnType("date")
                                .HasColumnName("booked_on");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("currency");

                            b1.Property<string>("Reason")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("reason");

                            b1.Property<int>("Type")
                                .HasColumnType("integer")
                                .HasColumnName("type");

                            b1.HasKey("LcId", "Id")
                                .HasName("pk_lc_margin_ledger");

                            b1.ToTable("lc_margin_ledger", "tradefin");

                            b1.WithOwner()
                                .HasForeignKey("LcId")
                                .HasConstraintName("fk_lc_margin_ledger_letters_of_credit_lc_id");
                        });

                    b.OwnsMany("ProcureFlow.Modules.TradeFinance.Domain.Entities.MaturityObligation", "Maturities", b1 =>
                        {
                            b1.Property<Guid>("LcId")
                                .HasColumnType("uuid")
                                .HasColumnName("lc_id");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("currency");

                            b1.Property<DateOnly>("DueDate")
                                .HasColumnType("date")
                                .HasColumnName("due_date");

                            b1.Property<int>("Status")
                                .HasColumnType("integer")
                                .HasColumnName("status");

                            b1.HasKey("LcId", "Id")
                                .HasName("pk_lc_maturities");

                            b1.ToTable("lc_maturities", "tradefin");

                            b1.WithOwner()
                                .HasForeignKey("LcId")
                                .HasConstraintName("fk_lc_maturities_letters_of_credit_lc_id");
                        });

                    b.Navigation("Amendments");

                    b.Navigation("Charges");

                    b.Navigation("MarginLedger");

                    b.Navigation("Maturities");

                    b.Navigation("Presentations");
                });
#pragma warning restore 612, 618
        }
    }
}
