<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Cobytelabs.Modulus.Core" Version="1.2.0" />
    <PackageReference Include="Cobytelabs.Modulus.EntityFrameworkCore" Version="1.2.0" />
    <PackageReference Include="Cobytelabs.Modulus.Events" Version="1.2.0" />
    <PackageReference Include="Cobytelabs.Modulus.Data.Abstractions" Version="1.2.0" />
    <PackageReference Include="Cobytelabs.Modulus.Data.PostgreSQL" Version="1.2.0" />
    <PackageReference Include="Cobytelabs.Modulus.Storage.S3" Version="1.2.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.9">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../ModulusSample.Modules.Media.Application/ModulusSample.Modules.Media.Application.csproj" />
    <ProjectReference Include="../ModulusSample.Modules.Media.Domain/ModulusSample.Modules.Media.Domain.csproj" />
    <ProjectReference Include="../../../Shared/ModulusSample.Shared.Infrastructure/ModulusSample.Shared.Infrastructure.csproj" />
  </ItemGroup>

</Project>
