// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModulusSample.Modules.Purchasing.Infrastructure.Database;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ModulusSample.Modules.Purchasing.Infrastructure.Database.Migrations
{
    [DbContext(typeof(PurchasingDbContext))]
    partial class PurchasingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("purchasing")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Modulus.Outbox.Abstractions.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CausationId")
                        .HasColumnType("text")
                        .HasColumnName("causation_id");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("text")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("LockedBy")
                        .HasColumnType("text")
                        .HasColumnName("locked_by");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("message_type");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("module_name");

                    b.Property<DateTime?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_outbox_messages_tenant_id");

                    b.HasIndex("ProcessedAt", "CreatedAt")
                        .HasDatabaseName("ix_outbox_messages_processed_at_created_at");

                    b.HasIndex("ProcessedAt", "LockedUntil", "RetryCount")
                        .HasDatabaseName("ix_outbox_messages_processed_at_locked_until_retry_count");

                    b.ToTable("outbox_messages", "purchasing");
                });

            modelBuilder.Entity("ModulusSample.Modules.Purchasing.Domain.Entities.GoodsReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("OrgUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_unit_id");

                    b.Property<Guid>("PurchaseOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("purchase_order_id");

                    b.Property<string>("ReceiptNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("receipt_number");

                    b.Property<DateTime>("ReceivedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_receipts");

                    b.ToTable("receipts", "purchasing");
                });

            modelBuilder.Entity("ModulusSample.Modules.Purchasing.Domain.Entities.PurchaseOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("order_number");

                    b.Property<Guid>("OrgUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_unit_id");

                    b.Property<Guid>("RequisitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("requisition_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("total_amount");

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.ToTable("orders", "purchasing");
                });

            modelBuilder.Entity("ModulusSample.Modules.Purchasing.Domain.Entities.PurchaseRequisition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ApproverId")
                        .HasColumnType("uuid")
                        .HasColumnName("approver_id");

                    b.Property<Guid>("OrgUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_unit_id");

                    b.Property<Guid>("RequesterId")
                        .HasColumnType("uuid")
                        .HasColumnName("requester_id");

                    b.Property<string>("RequisitionNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("requisition_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("total_amount");

                    b.HasKey("Id")
                        .HasName("pk_requisitions");

                    b.ToTable("requisitions", "purchasing");
                });

            modelBuilder.Entity("ModulusSample.Modules.Purchasing.Domain.Entities.GoodsReceipt", b =>
                {
                    b.OwnsMany("ModulusSample.Modules.Purchasing.Domain.Entities.ReceiptLine", "Lines", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("LotNumber")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("lot_number");

                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid")
                                .HasColumnName("product_id");

                            b1.Property<decimal>("QuantityReceived")
                                .HasColumnType("numeric")
                                .HasColumnName("quantity_received");

                            b1.Property<Guid>("ReceiptId")
                                .HasColumnType("uuid")
                                .HasColumnName("receipt_id");

                            b1.HasKey("Id")
                                .HasName("pk_receipt_lines");

                            b1.HasIndex("ReceiptId")
                                .HasDatabaseName("ix_receipt_lines_receipt_id");

                            b1.ToTable("ReceiptLines", "purchasing");

                            b1.WithOwner()
                                .HasForeignKey("ReceiptId")
                                .HasConstraintName("fk_receipt_lines_receipts_receipt_id");
                        });

                    b.Navigation("Lines");
                });

            modelBuilder.Entity("ModulusSample.Modules.Purchasing.Domain.Entities.PurchaseOrder", b =>
                {
                    b.OwnsMany("ModulusSample.Modules.Purchasing.Domain.Entities.PurchaseOrderLine", "Lines", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uuid")
                                .HasColumnName("order_id");

                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid")
                                .HasColumnName("product_id");

                            b1.Property<decimal>("Quantity")
                                .HasColumnType("numeric")
                                .HasColumnName("quantity");

                            b1.Property<decimal>("ReceivedQuantity")
                                .HasColumnType("numeric")
                                .HasColumnName("received_quantity");

                            b1.Property<decimal>("UnitPrice")
                                .HasColumnType("numeric")
                                .HasColumnName("unit_price");

                            b1.HasKey("Id")
                                .HasName("pk_order_lines");

                            b1.HasIndex("OrderId")
                                .HasDatabaseName("ix_order_lines_order_id");

                            b1.ToTable("OrderLines", "purchasing");

                            b1.WithOwner()
                                .HasForeignKey("OrderId")
                                .HasConstraintName("fk_order_lines_orders_order_id");
                        });

                    b.Navigation("Lines");
                });

            modelBuilder.Entity("ModulusSample.Modules.Purchasing.Domain.Entities.PurchaseRequisition", b =>
                {
                    b.OwnsMany("ModulusSample.Modules.Purchasing.Domain.Entities.RequisitionLine", "Lines", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("description");

                            b1.Property<decimal>("Quantity")
                                .HasColumnType("numeric")
                                .HasColumnName("quantity");

                            b1.Property<Guid>("RequisitionId")
                                .HasColumnType("uuid")
                                .HasColumnName("requisition_id");

                            b1.Property<Guid>("SupplierId")
                                .HasColumnType("uuid")
                                .HasColumnName("supplier_id");

                            b1.Property<decimal>("UnitPrice")
                                .HasColumnType("numeric")
                                .HasColumnName("unit_price");

                            b1.HasKey("Id")
                                .HasName("pk_requisition_lines");

                            b1.HasIndex("RequisitionId")
                                .HasDatabaseName("ix_requisition_lines_requisition_id");

                            b1.ToTable("RequisitionLines", "purchasing");

                            b1.WithOwner()
                                .HasForeignKey("RequisitionId")
                                .HasConstraintName("fk_requisition_lines_requisitions_requisition_id");
                        });

                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
