<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="../../../src/data/Modulus.Data.PostgreSQL/Modulus.Data.PostgreSQL.csproj" />
    <ProjectReference Include="../../../src/data/Modulus.EntityFrameworkCore/Modulus.EntityFrameworkCore.csproj" />
    <PackageReference Include="Testcontainers.PostgreSql" />
  </ItemGroup>

</Project>
