<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="../../../src/platform/Modulus.Platform/Modulus.Platform.csproj" />
    <ProjectReference Include="../../../src/platform/Modulus.MultiTenancy.EntityFrameworkCore/Modulus.MultiTenancy.EntityFrameworkCore.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
  </ItemGroup>

</Project>
