// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TradeFlow.Modules.Customs.Infrastructure.Database;

#nullable disable

namespace TradeFlow.Modules.Customs.Infrastructure.Migrations
{
    [DbContext(typeof(CustomsDbContext))]
    [Migration("20260901043401_AddAitAtAdjustmentFields")]
    partial class AddAitAtAdjustmentFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("customs")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Modulus.Outbox.Abstractions.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CausationId")
                        .HasColumnType("text")
                        .HasColumnName("causation_id");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("text")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("LockedBy")
                        .HasColumnType("text")
                        .HasColumnName("locked_by");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("message_type");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("module_name");

                    b.Property<DateTime?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_outbox_messages_tenant_id");

                    b.HasIndex("ProcessedAt", "CreatedAt")
                        .HasDatabaseName("ix_outbox_messages_processed_at_created_at");

                    b.HasIndex("ProcessedAt", "LockedUntil", "RetryCount")
                        .HasDatabaseName("ix_outbox_messages_processed_at_locked_until_retry_count");

                    b.ToTable("outbox_messages", "customs");
                });

            modelBuilder.Entity("TradeFlow.Modules.Customs.Domain.Entities.AitAtLedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount");

                    b.Property<Guid?>("BoeId")
                        .HasColumnType("uuid")
                        .HasColumnName("boe_id");

                    b.Property<DateOnly>("BookedOn")
                        .HasColumnType("date")
                        .HasColumnName("booked_on");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<int>("Component")
                        .HasColumnType("integer")
                        .HasColumnName("component");

                    b.Property<int>("EntryType")
                        .HasColumnType("integer")
                        .HasColumnName("entry_type");

                    b.Property<Guid?>("FileId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_id");

                    b.Property<int>("FiscalYear")
                        .HasColumnType("integer")
                        .HasColumnName("fiscal_year");

                    b.Property<string>("Narrative")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("narrative");

                    b.Property<string>("ReturnPeriod")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("return_period");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_ait_at_ledger");

                    b.HasIndex("CompanyId", "FiscalYear", "Component")
                        .HasDatabaseName("ix_ait_at_ledger_company_id_fiscal_year_component");

                    b.ToTable("ait_at_ledger", "customs");
                });

            modelBuilder.Entity("TradeFlow.Modules.Customs.Domain.Entities.BillOfEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("BoeDate")
                        .HasColumnType("date")
                        .HasColumnName("boe_date");

                    b.Property<string>("BoeNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("boe_no");

                    b.Property<string>("DeclarantAin")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("declarant_ain");

                    b.Property<Guid?>("FileId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_id");

                    b.Property<int?>("Lane")
                        .HasColumnType("integer")
                        .HasColumnName("lane");

                    b.Property<string>("OfficeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("office_code");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal?>("TolerancePct")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("tolerance_pct");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_bills_of_entry");

                    b.HasIndex("TenantId", "BoeNo")
                        .IsUnique()
                        .HasDatabaseName("ix_bills_of_entry_tenant_id_boe_no");

                    b.ToTable("bills_of_entry", "customs");
                });

            modelBuilder.Entity("TradeFlow.Modules.Customs.Domain.Entities.DemurrageAccrual", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AccruedAmountBdt")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("accrued_amount_bdt");

                    b.Property<int>("AccruedDays")
                        .HasColumnType("integer")
                        .HasColumnName("accrued_days");

                    b.Property<string>("ContainerRef")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("container_ref");

                    b.Property<decimal>("DailyRateBdt")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("daily_rate_bdt");

                    b.Property<Guid?>("FileId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_id");

                    b.Property<int>("FreeDays")
                        .HasColumnType("integer")
                        .HasColumnName("free_days");

                    b.Property<DateOnly>("LandingDate")
                        .HasColumnType("date")
                        .HasColumnName("landing_date");

                    b.Property<string>("PortCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("port_code");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_demurrage_accruals");

                    b.HasIndex("TenantId", "FileId")
                        .HasDatabaseName("ix_demurrage_accruals_tenant_id_file_id");

                    b.ToTable("demurrage_accruals", "customs");
                });

            modelBuilder.Entity("TradeFlow.Modules.Customs.Domain.Entities.DutyRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ApprovedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at_utc");

                    b.Property<string>("Checker")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("checker");

                    b.Property<int>("Component")
                        .HasColumnType("integer")
                        .HasColumnName("component");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("effective_from");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date")
                        .HasColumnName("effective_to");

                    b.Property<string>("HsCode")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("hs_code");

                    b.Property<string>("Maker")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("maker");

                    b.Property<decimal>("Rate")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("rate");

                    b.Property<string>("RefDoc")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ref_doc");

                    b.Property<int>("Source")
                        .HasColumnType("integer")
                        .HasColumnName("source");

                    b.Property<decimal?>("SpecificRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("specific_rate");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Uom")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("uom");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_duty_rates");

                    b.HasIndex("HsCode", "Component", "EffectiveFrom")
                        .HasDatabaseName("ix_duty_rates_hs_code_component_effective_from");

                    b.ToTable("duty_rates", "customs");
                });

            modelBuilder.Entity("TradeFlow.Modules.Customs.Domain.Entities.HsCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("effective_from");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date")
                        .HasColumnName("effective_to");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_hs_codes");

                    b.HasIndex("Code", "EffectiveFrom")
                        .IsUnique()
                        .HasDatabaseName("ix_hs_codes_code_effective_from");

                    b.ToTable("hs_codes", "customs");
                });

            modelBuilder.Entity("TradeFlow.Modules.Customs.Domain.Entities.ItemHsMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ApprovedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at_utc");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by");

                    b.Property<decimal>("Confidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("confidence");

                    b.Property<string>("HsCode")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("hs_code");

                    b.Property<bool>("IsConsignmentOverride")
                        .HasColumnType("boolean")
                        .HasColumnName("is_consignment_override");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<DateTime?>("MappedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("mapped_at_utc");

                    b.Property<Guid?>("MappedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("mapped_by");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<Guid?>("OverrideFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("override_file_id");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("rejection_reason");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_item_hs_mappings");

                    b.HasIndex("TenantId", "HsCode")
                        .HasDatabaseName("ix_item_hs_mappings_tenant_id_hs_code");

                    b.HasIndex("TenantId", "ItemId")
                        .IsUnique()
                        .HasDatabaseName("ix_item_hs_mappings_tenant_id_item_id");

                    b.ToTable("item_hs_mappings", "customs");
                });

            modelBuilder.Entity("TradeFlow.Modules.Customs.Domain.Entities.SroBenefit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("CapPercent")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("cap_percent");

                    b.Property<string>("Conditions")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("conditions");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("effective_from");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date")
                        .HasColumnName("effective_to");

                    b.Property<string>("HsCodePrefix")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("hs_code_prefix");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<decimal?>("OverrideRate")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("override_rate");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_sro_benefits");

                    b.ToTable("sro_benefits", "customs");
                });

            modelBuilder.Entity("TradeFlow.Modules.Customs.Domain.Entities.BillOfEntry", b =>
                {
                    b.OwnsMany("TradeFlow.Modules.Customs.Domain.Entities.BoeLine", "Lines", b1 =>
                        {
                            b1.Property<Guid>("BoeId")
                                .HasColumnType("uuid")
                                .HasColumnName("boe_id");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal?>("AssessedTtiBdt")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("assessed_tti_bdt");

                            b1.Property<Guid?>("CiLineId")
                                .HasColumnType("uuid")
                                .HasColumnName("ci_line_id");

                            b1.Property<decimal?>("ComputedTtiBdt")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("computed_tti_bdt");

                            b1.Property<decimal>("CustomsExchangeRate")
                                .HasPrecision(18, 6)
                                .HasColumnType("numeric(18,6)")
                                .HasColumnName("customs_exchange_rate");

                            b1.Property<decimal>("DeclaredAvFcy")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("declared_av_fcy");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("description");

                            b1.Property<string>("HsCode")
                                .IsRequired()
                                .HasMaxLength(12)
                                .HasColumnType("character varying(12)")
                                .HasColumnName("hs_code");

                            b1.Property<decimal>("LandingChargePct")
                                .HasPrecision(9, 6)
                                .HasColumnType("numeric(9,6)")
                                .HasColumnName("landing_charge_pct");

                            b1.Property<decimal>("Quantity")
                                .HasColumnType("numeric")
                                .HasColumnName("quantity");

                            b1.Property<decimal?>("TariffValueBdt")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("tariff_value_bdt");

                            b1.Property<string>("Uom")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("uom");

                            b1.HasKey("BoeId", "Id")
                                .HasName("pk_boe_lines");

                            b1.HasIndex("HsCode")
                                .HasDatabaseName("ix_boe_lines_hs_code");

                            b1.ToTable("boe_lines", "customs");

                            b1.WithOwner()
                                .HasForeignKey("BoeId")
                                .HasConstraintName("fk_boe_lines_bills_of_entry_boe_id");

                            b1.OwnsMany("TradeFlow.Modules.Customs.Domain.Entities.AssessedDutyLine", "AssessedDutyLines", b2 =>
                                {
                                    b2.Property<Guid>("BoeId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("boe_id");

                                    b2.Property<Guid>("BoeLineId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("boe_line_id");

                                    b2.Property<Guid>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 4)
                                        .HasColumnType("numeric(18,4)")
                                        .HasColumnName("amount");

                                    b2.Property<string>("Component")
                                        .IsRequired()
                                        .HasMaxLength(10)
                                        .HasColumnType("character varying(10)")
                                        .HasColumnName("component");

                                    b2.HasKey("BoeId", "BoeLineId", "Id")
                                        .HasName("pk_boe_line_assessed_duties");

                                    b2.ToTable("boe_line_assessed_duties", "customs");

                                    b2.WithOwner()
                                        .HasForeignKey("BoeId", "BoeLineId")
                                        .HasConstraintName("fk_boe_line_assessed_duties_boe_lines_boe_id_boe_line_id");
                                });

                            b1.OwnsMany("TradeFlow.Modules.Customs.Domain.Entities.RateLineageRow", "RateLineage", b2 =>
                                {
                                    b2.Property<Guid>("BoeId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("boe_id");

                                    b2.Property<Guid>("BoeLineId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("boe_line_id");

                                    b2.Property<Guid>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<string>("Component")
                                        .IsRequired()
                                        .HasMaxLength(10)
                                        .HasColumnType("character varying(10)")
                                        .HasColumnName("component");

                                    b2.Property<Guid>("RateRowId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("rate_row_id");

                                    b2.Property<decimal>("RateUsed")
                                        .HasColumnType("numeric")
                                        .HasColumnName("rate_used");

                                    b2.HasKey("BoeId", "BoeLineId", "Id")
                                        .HasName("pk_boe_line_rate_lineage");

                                    b2.ToTable("boe_line_rate_lineage", "customs");

                                    b2.WithOwner()
                                        .HasForeignKey("BoeId", "BoeLineId")
                                        .HasConstraintName("fk_boe_line_rate_lineage_boe_lines_boe_id_boe_line_id");
                                });

                            b1.Navigation("AssessedDutyLines");

                            b1.Navigation("RateLineage");
                        });

                    b.OwnsMany("TradeFlow.Modules.Customs.Domain.Entities.Challan", "Challans", b1 =>
                        {
                            b1.Property<Guid>("BoeId")
                                .HasColumnType("uuid")
                                .HasColumnName("boe_id");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("amount");

                            b1.Property<string>("ChallanNo")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("challan_no");

                            b1.Property<string>("EvidenceRef")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("evidence_ref");

                            b1.Property<DateTime>("PaidAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("paid_at_utc");

                            b1.HasKey("BoeId", "Id")
                                .HasName("pk_boe_challans");

                            b1.ToTable("boe_challans", "customs");

                            b1.WithOwner()
                                .HasForeignKey("BoeId")
                                .HasConstraintName("fk_boe_challans_bills_of_entry_boe_id");
                        });

                    b.OwnsMany("TradeFlow.Modules.Customs.Domain.Entities.ClearanceMilestone", "Milestones", b1 =>
                        {
                            b1.Property<Guid>("BoeId")
                                .HasColumnType("uuid")
                                .HasColumnName("boe_id");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<DateTime>("OccurredAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("occurred_at_utc");

                            b1.Property<string>("Stage")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("stage");

                            b1.HasKey("BoeId", "Id")
                                .HasName("pk_boe_milestones");

                            b1.ToTable("boe_milestones", "customs");

                            b1.WithOwner()
                                .HasForeignKey("BoeId")
                                .HasConstraintName("fk_boe_milestones_bills_of_entry_boe_id");
                        });

                    b.OwnsMany("TradeFlow.Modules.Customs.Domain.Entities.DisputeRecord", "Disputes", b1 =>
                        {
                            b1.Property<Guid>("BoeId")
                                .HasColumnType("uuid")
                                .HasColumnName("boe_id");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("BoeLineId")
                                .HasColumnType("uuid")
                                .HasColumnName("boe_line_id");

                            b1.Property<string>("GuaranteeRef")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("guarantee_ref");

                            b1.Property<string>("Notes")
                                .HasColumnType("text")
                                .HasColumnName("notes");

                            b1.Property<int>("ResolutionType")
                                .HasColumnType("integer")
                                .HasColumnName("resolution_type");

                            b1.Property<DateTime?>("ResolvedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("resolved_at");

                            b1.Property<int>("Status")
                                .HasColumnType("integer")
                                .HasColumnName("status");

                            b1.Property<decimal>("TolerancePct")
                                .HasPrecision(9, 6)
                                .HasColumnType("numeric(9,6)")
                                .HasColumnName("tolerance_pct");

                            b1.Property<decimal>("VarianceAmount")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("variance_amount");

                            b1.HasKey("BoeId", "Id")
                                .HasName("pk_boe_disputes");

                            b1.ToTable("boe_disputes", "customs");

                            b1.WithOwner()
                                .HasForeignKey("BoeId")
                                .HasConstraintName("fk_boe_disputes_bills_of_entry_boe_id");
                        });

                    b.Navigation("Challans");

                    b.Navigation("Disputes");

                    b.Navigation("Lines");

                    b.Navigation("Milestones");
                });
#pragma warning restore 612, 618
        }
    }
}
