<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="../../../src/platform/Modulus.Grpc/Modulus.Grpc.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Grpc.Tools" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="Protos/probe.proto" GrpcServices="Both" />
  </ItemGroup>

</Project>
