// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TradeFlow.Modules.WorkflowEngine.Infrastructure.Database;

#nullable disable

namespace TradeFlow.Modules.WorkflowEngine.Infrastructure.Database.Migrations
{
    [DbContext(typeof(WorkflowDbContext))]
    [Migration("20260831093423_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("workflow_engine")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Modulus.Outbox.Abstractions.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CausationId")
                        .HasColumnType("text")
                        .HasColumnName("causation_id");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("text")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("LockedBy")
                        .HasColumnType("text")
                        .HasColumnName("locked_by");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("message_type");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("module_name");

                    b.Property<DateTime?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_outbox_messages_tenant_id");

                    b.HasIndex("ProcessedAt", "CreatedAt")
                        .HasDatabaseName("ix_outbox_messages_processed_at_created_at");

                    b.HasIndex("ProcessedAt", "LockedUntil", "RetryCount")
                        .HasDatabaseName("ix_outbox_messages_processed_at_locked_until_retry_count");

                    b.ToTable("outbox_messages", "workflow_engine");
                });

            modelBuilder.Entity("TradeFlow.Modules.WorkflowEngine.Domain.Entities.WorkflowDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContextSchemaJson")
                        .HasColumnType("text")
                        .HasColumnName("context_schema_json");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("document_type");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.Property<string>("OnRejectJson")
                        .HasColumnType("text")
                        .HasColumnName("on_reject_json");

                    b.Property<string>("OnTimeoutAction")
                        .HasColumnType("text")
                        .HasColumnName("on_timeout_action");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at_utc");

                    b.Property<string>("PublishedBy")
                        .HasColumnType("text")
                        .HasColumnName("published_by");

                    b.Property<int>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("StepsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("steps_json");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TriggerEvent")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("trigger_event");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_workflow_definitions");

                    b.HasIndex("TenantId", "Key", "Status")
                        .HasDatabaseName("ix_workflow_definitions_tenant_id_key_status");

                    b.HasIndex("TenantId", "Key", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_workflow_definitions_tenant_id_key_version");

                    b.ToTable("workflow_definitions", "workflow_engine");
                });

            modelBuilder.Entity("TradeFlow.Modules.WorkflowEngine.Domain.Entities.WorkflowEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Actor")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("actor");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_type");

                    b.Property<Guid>("InstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("instance_id");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("text")
                        .HasColumnName("payload_json");

                    b.Property<Guid?>("WorkflowInstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_instance_id");

                    b.HasKey("Id")
                        .HasName("pk_workflow_events");

                    b.HasIndex("InstanceId")
                        .HasDatabaseName("ix_workflow_events_instance_id");

                    b.HasIndex("WorkflowInstanceId")
                        .HasDatabaseName("ix_workflow_events_workflow_instance_id");

                    b.ToTable("workflow_events", "workflow_engine");
                });

            modelBuilder.Entity("TradeFlow.Modules.WorkflowEngine.Domain.Entities.WorkflowInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<string>("CompletedBy")
                        .HasColumnType("text")
                        .HasColumnName("completed_by");

                    b.Property<string>("ContextJson")
                        .HasColumnType("text")
                        .HasColumnName("context_json");

                    b.Property<Guid>("DefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("definition_id");

                    b.Property<string>("DefinitionKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("definition_key");

                    b.Property<int>("DefinitionVersion")
                        .HasColumnType("integer")
                        .HasColumnName("definition_version");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("document_type");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("state");

                    b.Property<int>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_workflow_instances");

                    b.HasIndex("DefinitionId")
                        .HasDatabaseName("ix_workflow_instances_definition_id");

                    b.HasIndex("TenantId", "DocumentType", "DocumentId")
                        .HasDatabaseName("ix_workflow_instances_tenant_id_document_type_document_id");

                    b.ToTable("workflow_instances", "workflow_engine");
                });

            modelBuilder.Entity("TradeFlow.Modules.WorkflowEngine.Domain.Entities.WorkflowTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ActedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acted_at_utc");

                    b.Property<Guid?>("ActedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("acted_by_user_id");

                    b.Property<string>("AssigneeResolutionJson")
                        .HasColumnType("text")
                        .HasColumnName("assignee_resolution_json");

                    b.Property<string>("AssigneeRole")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("assignee_role");

                    b.Property<Guid?>("AssigneeUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignee_user_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int?>("Decision")
                        .HasMaxLength(50)
                        .HasColumnType("integer")
                        .HasColumnName("decision");

                    b.Property<DateTime?>("DueAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_at_utc");

                    b.Property<Guid>("InstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("instance_id");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<int>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("StepId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("step_id");

                    b.Property<string>("StepType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("step_type");

                    b.Property<Guid?>("WorkflowInstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_instance_id");

                    b.HasKey("Id")
                        .HasName("pk_workflow_tasks");

                    b.HasIndex("InstanceId")
                        .HasDatabaseName("ix_workflow_tasks_instance_id");

                    b.HasIndex("WorkflowInstanceId")
                        .HasDatabaseName("ix_workflow_tasks_workflow_instance_id");

                    b.HasIndex("AssigneeUserId", "Status")
                        .HasDatabaseName("ix_workflow_tasks_assignee_user_id_status");

                    b.ToTable("workflow_tasks", "workflow_engine");
                });

            modelBuilder.Entity("TradeFlow.Modules.WorkflowEngine.Domain.Entities.WorkflowEvent", b =>
                {
                    b.HasOne("TradeFlow.Modules.WorkflowEngine.Domain.Entities.WorkflowInstance", null)
                        .WithMany("Events")
                        .HasForeignKey("WorkflowInstanceId")
                        .HasConstraintName("fk_workflow_events_workflow_instances_workflow_instance_id");
                });

            modelBuilder.Entity("TradeFlow.Modules.WorkflowEngine.Domain.Entities.WorkflowTask", b =>
                {
                    b.HasOne("TradeFlow.Modules.WorkflowEngine.Domain.Entities.WorkflowInstance", null)
                        .WithMany("Tasks")
                        .HasForeignKey("WorkflowInstanceId")
                        .HasConstraintName("fk_workflow_tasks_workflow_instances_workflow_instance_id");
                });

            modelBuilder.Entity("TradeFlow.Modules.WorkflowEngine.Domain.Entities.WorkflowInstance", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
