using System.ComponentModel;
using System.Text.RegularExpressions;
using Modulus.Cli.Services;
using Spectre.Console;
using Spectre.Console.Cli;

namespace Modulus.Cli.Commands;

/// <summary>
/// <c>modulus generate-graphql Product [--module Catalog] [--bff mobile|all]</c>: exposes an entity's generated CRUD commands
/// and queries over GraphQL. It writes the graph type (<c>GraphQL/{Entity}GraphType.cs</c>) and the module's contributor
/// (<c>GraphQL/{Entity}GraphQL.cs</c>: list and get queries, create/update/delete mutations through <c>IMediator</c>, under the
/// same permission as the HTTP endpoints) into the module's Presentation project, wires the API host (<c>AddModulusGraphQL</c>
/// over the Presentation assemblies, <c>MapModulusGraphQL</c>, the <c>GraphQL</c> settings), adds a test class, and, with
/// <c>--bff</c>, routes <c>/graphql</c> through those BFFs to the API. Existing files are never overwritten; edits are idempotent.
/// </summary>
internal sealed partial class GenerateGraphQLCommand : Command<GenerateGraphQLCommand.Settings>
{
    private readonly TemplateEngine _templates = new();

    internal sealed class Settings : ModulusSettings
    {
        [Description("The entity whose CRUD set to expose (generated by generate-crud), e.g. Product.")]
        [CommandArgument(0, "<entity>")]
        public string Entity { get; init; } = "";

        [Description("The module that owns the entity. Default: the module that has it.")]
        [CommandOption("-m|--module")]
        public string? Module { get; init; }

        [Description("BFFs that proxy /graphql to the API (web, mobile, partner; comma-separated, or all).")]
        [CommandOption("--bff")]
        public string? Bff { get; init; }
    }

    public override int Execute(CommandContext ctx, Settings s)
    {
        s.Apply();
        return CommandRunner.Run(() => new GenerateGraphQLCommand().ExecuteCore(s, Environment.CurrentDirectory));
    }

    internal int ExecuteCore(Settings s, string startDir)
    {
        if (!PascalCase().IsMatch(s.Entity))
            throw new ArgumentException($"'{s.Entity}' is not a PascalCase entity name (e.g. Product).");

        var app = ModuleDiscovery.Inventory(startDir)
            ?? throw new InvalidOperationException("No .slnx file found in the current directory tree. Run this command from within a Modulus application.");

        var module = GenerateGrpcCommand.FindModule(app.Modules, s.Entity, s.Module);
        var bffs = GenerateGrpcCommand.SelectBffs(app.Bffs, s.Bff);
        var plural = CodeGen.Pluralize(s.Entity);
        var presDir = CodeGen.LayerDir(module.Directory, module.Namespace, "Presentation");
        var presCsproj = Path.Combine(presDir, $"{module.Namespace}.Presentation.csproj");
        var endpointFile = Path.Combine(presDir, $"{plural}Endpoint.cs");
        if (!File.Exists(endpointFile) || !File.Exists(presCsproj))
            throw new InvalidOperationException($"No CRUD set for {s.Entity} in {module.Name} ({plural}Endpoint.cs). Run: modulus generate-crud {s.Entity} --module {module.Name}.");

        var model = Model(app.RootNamespace, module, s.Entity, plural, GenerateGrpcCommand.ReadPermission(File.ReadAllText(endpointFile)));
        var apiDir = Path.GetDirectoryName(app.ApiProjectPath)!;
        var written = new List<string>();
        var hints = new List<string>();

        // ── Module: graph type, contributor, project ────────────────
        Write("graphql/GraphType", model, Path.Combine(presDir, "GraphQL", $"{s.Entity}GraphType.cs"), Relative(app, presDir, $"GraphQL/{s.Entity}GraphType.cs"), written);
        Write("graphql/Contributor", model, Path.Combine(presDir, "GraphQL", $"{s.Entity}GraphQL.cs"), Relative(app, presDir, $"GraphQL/{s.Entity}GraphQL.cs"), written);
        Edit(presCsproj, t => GraphQLWiring.EnsurePresentationProject(t, FrameworkVersion.Current), written, app);

        // ── API host ────────────────────────────────────────────────
        if (ProjectFileService.EnsureCsprojPackageReference(app.ApiProjectPath, GraphQLWiring.PackageId, FrameworkVersion.Current, Ux.DryRun))
            written.Add(Path.GetRelativePath(app.SolutionDir, app.ApiProjectPath) + " (updated)");
        if (!Edit(app.ProgramCsPath, t => GraphQLWiring.EnsureApiProgram(t, app.RootNamespace), written, app)
            && !File.ReadAllText(app.ProgramCsPath).Contains("MapModulusGraphQL(", StringComparison.Ordinal))
        {
            hints.Add("Program.cs: add builder.Services.AddModulusGraphQL(builder.Configuration, <Presentation assemblies>); before Build() and app.MapModulusGraphQL(); after the endpoints.");
        }

        Edit(Path.Combine(apiDir, "appsettings.json"), t => GraphQLWiring.EnsureApiSettings(t, development: false), written, app);
        Edit(Path.Combine(apiDir, "appsettings.Development.json"), t => GraphQLWiring.EnsureApiSettings(t, development: true), written, app);

        // ── Tests ───────────────────────────────────────────────────
        var testsDir = Path.Combine(app.SolutionDir, "tests", $"{app.RootNamespace}.Tests");
        if (Directory.Exists(testsDir))
            Write("graphql/GraphQLTests", model, Path.Combine(testsDir, $"{s.Entity}GraphQLTests.cs"), $"tests/{app.RootNamespace}.Tests/{s.Entity}GraphQLTests.cs", written);

        // ── BFFs: /graphql proxied to the API under each BFF's edge rules ──
        foreach (var bff in bffs)
        {
            if (!Edit(bff.AppSettings, t => GraphQLWiring.EnsureBffRemoteApi(t), written, app)
                && !(File.Exists(bff.AppSettings) && File.ReadAllText(bff.AppSettings).Contains("\"/graphql\"", StringComparison.Ordinal)))
            {
                hints.Add($"{bff.ProjectName}: add {{ \"LocalPath\": \"/graphql\", \"Service\": \"api\" }} to Bff:Clients:<client>:RemoteApis.");
            }
        }

        AnsiConsole.MarkupLine("[green]✓[/] [cyan]{0}[/] over GraphQL in the [cyan]{1}[/] module", s.Entity, module.Name);
        foreach (var f in written.Distinct())
            AnsiConsole.MarkupLine("  [green]→[/] [grey]{0}[/]", Markup.Escape(f));
        foreach (var hint in hints)
            AnsiConsole.MarkupLine("  [yellow]![/] {0}", Markup.Escape(hint));
        if (bffs.Count > 0)
            AnsiConsole.MarkupLine("  [grey]Through a BFF: POST /graphql on the BFF (the web BFF also needs the X-CSRF: 1 header, like its other proxied calls).[/]");
        AnsiConsole.MarkupLine("  [grey]Development: POST /graphql with a bearer token; GraphiQL at /graphql/ui (add the Authorization header in its header editor).[/]");
        return 0;
    }

    internal static GraphQLModel Model(string rootNamespace, ModuleDiscovery.ModuleSummary module, string entity, string plural, string? permission)
        => new()
        {
            RootNamespace = rootNamespace,
            ModuleNamespace = module.Namespace,
            ModuleName = module.Name,
            EntityName = entity,
            EntityNameLower = CodeGen.ToCamelCase(entity),
            EntityNameCamel = CodeGen.ToCamelCase(entity),
            EntityPlural = plural,
            EntityPluralCamel = CodeGen.ToCamelCase(plural),
            RequiredPermission = permission,
            AdminRole = UiAccessGates.AdminRole,
        };

    internal sealed class GraphQLModel
    {
        public string RootNamespace { get; init; } = "";
        public string ModuleNamespace { get; init; } = "";
        public string ModuleName { get; init; } = "";
        public string EntityName { get; init; } = "";
        public string EntityNameLower { get; init; } = "";
        public string EntityNameCamel { get; init; } = "";
        public string EntityPlural { get; init; } = "";
        public string EntityPluralCamel { get; init; } = "";
        public string? RequiredPermission { get; init; }
        public string AdminRole { get; init; } = "";

        /// <summary>The authorization call each field carries: the endpoints' permission, else a signed-in caller.</summary>
        public string Authorize => RequiredPermission is null ? ".Authorize()" : ".AuthorizeWithPolicy(Permission)";
    }

    private void Write(string template, GraphQLModel model, string path, string display, List<string> written)
    {
        if (File.Exists(path))
        {
            AnsiConsole.MarkupLine("  [yellow]•[/] [grey]{0}[/] [yellow](exists, skipped)[/]", Markup.Escape(display));
            return;
        }

        _templates.RenderToFile(template, model, path);
        written.Add(display);
    }

    // Applies a pure text edit; true when the file changed (and was written, unless --dry-run).
    private static bool Edit(string path, Func<string, string> edit, List<string> written, ModuleDiscovery.AppInventory app)
    {
        if (!File.Exists(path))
            return false;
        var before = File.ReadAllText(path);
        var after = edit(before);
        if (after == before)
            return false;
        Ux.WriteFile(path, after);
        written.Add(Path.GetRelativePath(app.SolutionDir, path).Replace('\\', '/') + " (updated)");
        return true;
    }

    private static string Relative(ModuleDiscovery.AppInventory app, string dir, string file)
        => Path.GetRelativePath(app.SolutionDir, Path.Combine(dir, file)).Replace('\\', '/');

    [GeneratedRegex("^[A-Z][A-Za-z0-9]*$")]
    private static partial Regex PascalCase();
}
