using System.ComponentModel;
using System.Text.RegularExpressions;
using Modulus.Cli.Services;
using Spectre.Console;
using Spectre.Console.Cli;

namespace Modulus.Cli.Commands;

/// <summary>
/// <c>modulus generate-grpc Product [--module Catalog] [--bff mobile|all]</c>: exposes an entity's generated CRUD commands and
/// queries over gRPC. It writes the contract (<c>Protos/{entity}.proto</c>) and the service (<c>Grpc/{Entity}GrpcService.cs</c>,
/// calling <c>IMediator</c> under the same permission as the HTTP endpoints) into the module's Presentation project, wires the
/// API host (<c>AddModulusGrpc</c>, <c>MapModulusGrpc</c>, the <c>Grpc</c> settings and a Development HTTP/2 endpoint), adds a
/// test class, and, with <c>--bff</c>, links the contract into BFFs as a client registered with <c>AddBffGrpcClient</c>.
/// Existing files are never overwritten; edits to existing files are idempotent.
/// </summary>
internal sealed partial class GenerateGrpcCommand : Command<GenerateGrpcCommand.Settings>
{
    private readonly TemplateEngine _templates = new();

    internal sealed class Settings : ModulusSettings
    {
        [Description("The entity whose CRUD set to expose (generated by generate-crud), e.g. Product.")]
        [CommandArgument(0, "<entity>")]
        public string Entity { get; init; } = "";

        [Description("The module that owns the entity. Default: the module that has it.")]
        [CommandOption("-m|--module")]
        public string? Module { get; init; }

        [Description("BFFs that call the service over gRPC (web, mobile, partner; comma-separated, or all).")]
        [CommandOption("--bff")]
        public string? Bff { get; init; }
    }

    public override int Execute(CommandContext ctx, Settings s)
    {
        s.Apply();
        return CommandRunner.Run(() => new GenerateGrpcCommand().ExecuteCore(s, Environment.CurrentDirectory));
    }

    internal int ExecuteCore(Settings s, string startDir)
    {
        if (!PascalCase().IsMatch(s.Entity))
            throw new ArgumentException($"'{s.Entity}' is not a PascalCase entity name (e.g. Product).");

        var app = ModuleDiscovery.Inventory(startDir)
            ?? throw new InvalidOperationException("No .slnx file found in the current directory tree. Run this command from within a Modulus application.");
        if (app.Kind == AppKind.WebApp)
            throw new InvalidOperationException("A web app maps no API surface, so it has nowhere to serve gRPC. Use an api or webapp+api app.");

        var module = FindModule(app.Modules, s.Entity, s.Module);
        var bffs = SelectBffs(app.Bffs, s.Bff);
        var plural = CodeGen.Pluralize(s.Entity);
        var presDir = CodeGen.LayerDir(module.Directory, module.Namespace, "Presentation");
        var presCsproj = Path.Combine(presDir, $"{module.Namespace}.Presentation.csproj");
        var endpointFile = Path.Combine(presDir, $"{plural}Endpoint.cs");
        if (!File.Exists(endpointFile) || !File.Exists(presCsproj))
            throw new InvalidOperationException($"No CRUD set for {s.Entity} in {module.Name} ({plural}Endpoint.cs). Run: modulus generate-crud {s.Entity} --module {module.Name}.");

        var model = Model(app.RootNamespace, module, s.Entity, plural, ReadPermission(File.ReadAllText(endpointFile)));
        var apiDir = Path.GetDirectoryName(app.ApiProjectPath)!;
        var written = new List<string>();
        var hints = new List<string>();

        // ── Module: contract, service, project ──────────────────────
        Write("grpc/Entity.proto", model, Path.Combine(presDir, "Protos", model.ProtoFile), Relative(app, presDir, $"Protos/{model.ProtoFile}"), written);
        Write("grpc/GrpcService", model, Path.Combine(presDir, "Grpc", $"{s.Entity}GrpcService.cs"), Relative(app, presDir, $"Grpc/{s.Entity}GrpcService.cs"), written);
        Edit(presCsproj, t => GrpcWiring.EnsurePresentationProject(t, FrameworkVersion.Current), written, app);

        // ── API host ────────────────────────────────────────────────
        if (ProjectFileService.EnsureCsprojPackageReference(app.ApiProjectPath, "Cobytelabs.Modulus.Grpc", FrameworkVersion.Current, Ux.DryRun))
            written.Add(Path.GetRelativePath(app.SolutionDir, app.ApiProjectPath) + " (updated)");
        if (!Edit(app.ProgramCsPath, t => GrpcWiring.EnsureApiProgram(t, app.RootNamespace), written, app)
            && !File.ReadAllText(app.ProgramCsPath).Contains("MapModulusGrpc(", StringComparison.Ordinal))
        {
            hints.Add("Program.cs: add builder.Services.AddModulusGrpc(builder.Configuration); before Build() and app.MapModulusGrpc(<Presentation assemblies>); after the endpoints.");
        }

        Edit(Path.Combine(apiDir, "appsettings.json"), t => GrpcWiring.EnsureApiSettings(t, development: false, 0), written, app);
        var devSettings = Path.Combine(apiDir, "appsettings.Development.json");
        if (File.Exists(devSettings))
        {
            var hadKestrel = GrpcWiring.HasKestrelSection(File.ReadAllText(devSettings));
            var port = GrpcWiring.ReadLaunchPort(apiDir) ?? 5180;
            Edit(devSettings, t => GrpcWiring.EnsureApiSettings(t, development: true, port), written, app);

            // The local token server must have one issuer across both endpoints, or gRPC callers' tokens are rejected.
            if (File.ReadAllText(app.ProgramCsPath).Contains("AddModulusOpenIddict(", StringComparison.Ordinal))
            {
                Edit(devSettings, t => GrpcWiring.EnsureIdentityIssuer(t, $"http://localhost:{port}/"), written, app);
                hints.Add("The API listens on two endpoints now: set Identity:Issuer to its public URL outside Development, so tokens are accepted on both.");
            }
            if (hadKestrel && !File.ReadAllText(devSettings).Contains($":{GrpcWiring.DevelopmentGrpcPort}", StringComparison.Ordinal))
                hints.Add($"appsettings.Development.json already configures Kestrel: add an endpoint with \"Protocols\": \"Http2\" (e.g. http://localhost:{GrpcWiring.DevelopmentGrpcPort}) for gRPC over plain HTTP.");
        }

        // ── Tests ───────────────────────────────────────────────────
        var testsDir = Path.Combine(app.SolutionDir, "tests", $"{app.RootNamespace}.Tests");
        if (Directory.Exists(testsDir))
            Write("grpc/GrpcTests", model, Path.Combine(testsDir, $"{s.Entity}GrpcTests.cs"), $"tests/{app.RootNamespace}.Tests/{s.Entity}GrpcTests.cs", written);

        // ── BFFs ────────────────────────────────────────────────────
        foreach (var bff in bffs)
        {
            foreach (var file in BffApiClients.EnsureModule(_templates, bff, module.Name, module.Entities))
                written.Add($"src/Bff/{bff.ProjectName}/{file}");

            var relative = Path.GetRelativePath(bff.Directory, presDir);
            Edit(bff.ProjectPath, t => GrpcWiring.EnsureBffProject(t, relative, module.Name), written, app);

            var service = BffModuleApiModel.ServiceFor(module.Name, BffApiClients.ReadServices(bff.AppSettings));
            var registration = Path.Combine(bff.Directory, "ApiClients", "ApiClientRegistration.cs");
            if (File.Exists(registration))
            {
                Edit(registration, t => GrpcWiring.EnsureBffRegistration(t, $"{s.Entity}Service.{s.Entity}ServiceClient", service, model.GrpcNamespace), written, app);
            }

            if (service == "api" && File.Exists(bff.AppSettings))
            {
                var grpcAddress = $"http://localhost:{GrpcWiring.DevelopmentGrpcPort}";
                Edit(bff.AppSettings, t => GrpcWiring.EnsureBffGrpcAddress(t, service, grpcAddress), written, app);
                if (!File.ReadAllText(bff.AppSettings).Contains("\"GrpcAddress\"", StringComparison.Ordinal))
                    hints.Add($"{bff.ProjectName}: set Bff:Services:api:GrpcAddress to the API's HTTP/2 endpoint ({grpcAddress} in Development).");
            }
            else
            {
                hints.Add($"{bff.ProjectName}: the '{service}' service needs an HTTP/2 endpoint for gRPC; set Bff:Services:{service}:GrpcAddress when its Address is plain HTTP/1.1.");
            }
        }

        AnsiConsole.MarkupLine("[green]✓[/] [cyan]{0}Service[/] over gRPC in the [cyan]{1}[/] module", s.Entity, module.Name);
        foreach (var f in written.Distinct())
            AnsiConsole.MarkupLine("  [green]→[/] [grey]{0}[/]", Markup.Escape(f));
        foreach (var hint in hints)
            AnsiConsole.MarkupLine("  [yellow]![/] {0}", Markup.Escape(hint));
        if (bffs.Count > 0)
            AnsiConsole.MarkupLine("  [grey]Inject {0}Service.{0}ServiceClient into a BFF endpoint; it carries the caller's token like the HTTP clients.[/]", s.Entity);
        AnsiConsole.MarkupLine("  [grey]Development: gRPC listens on http://localhost:{0} (HTTP/2 only); grpcurl -plaintext localhost:{0} list[/]", GrpcWiring.DevelopmentGrpcPort);
        return 0;
    }

    /// <summary>The module named by <c>--module</c>, else the one module whose entities include <paramref name="entity"/>.</summary>
    internal static ModuleDiscovery.ModuleSummary FindModule(IReadOnlyList<ModuleDiscovery.ModuleSummary> modules, string entity, string? option)
    {
        if (!string.IsNullOrWhiteSpace(option))
        {
            return modules.FirstOrDefault(m => string.Equals(m.Name, option, StringComparison.OrdinalIgnoreCase))
                ?? throw new ArgumentException($"Unknown module '{option}'. Modules: {string.Join(", ", modules.Select(m => m.Name))}.");
        }

        var owners = modules.Where(m => m.Entities.Contains(entity, StringComparer.Ordinal)).ToList();
        return owners.Count switch
        {
            1 => owners[0],
            0 => throw new ArgumentException($"No module has an entity named {entity}. Run modulus generate-crud {entity} --module <Module> first."),
            _ => throw new ArgumentException($"Several modules have an entity named {entity} ({string.Join(", ", owners.Select(m => m.Name))}); pick one with --module."),
        };
    }

    /// <summary>No option: none. <c>all</c>: every BFF. Otherwise the named clients, each of which must exist.</summary>
    internal static IReadOnlyList<BffApiClients.BffProject> SelectBffs(IReadOnlyList<BffApiClients.BffProject> bffs, string? option)
    {
        if (string.IsNullOrWhiteSpace(option))
            return [];
        if (string.Equals(option.Trim(), "all", StringComparison.OrdinalIgnoreCase))
        {
            return bffs.Count > 0
                ? bffs
                : throw new ArgumentException("The app has no BFF. Add one first: modulus add-bff web|mobile|partner.");
        }

        return GenerateBffEndpointCommand.SelectBffs(bffs, option);
    }

    /// <summary>The permission of the generated endpoints (<c>Permissions("...")</c>), or null when they have none.</summary>
    internal static string? ReadPermission(string endpointSource)
    {
        var match = PermissionCall().Match(endpointSource);
        return match.Success ? match.Groups[1].Value : null;
    }

    internal static GrpcModel Model(string rootNamespace, ModuleDiscovery.ModuleSummary module, string entity, string plural, string? permission)
    {
        var snake = ToSnakeCase(entity);
        return new GrpcModel
        {
            RootNamespace = rootNamespace,
            ModuleNamespace = module.Namespace,
            ModuleName = module.Name,
            EntityName = entity,
            EntityNameLower = CodeGen.ToCamelCase(entity),
            EntityPlural = plural,
            ProtoFile = snake + ".proto",
            ProtoPackage = $"{ToSnakeCase(rootNamespace.Replace(".", "", StringComparison.Ordinal))}.{ToSnakeCase(module.Name)}.v1",
            RequiredPermission = permission,
            AdminRole = UiAccessGates.AdminRole,
        };
    }

    /// <summary><c>ProductCategory</c> → <c>product_category</c>.</summary>
    internal static string ToSnakeCase(string pascal) => SnakeBoundary().Replace(pascal, "_$1").ToLowerInvariant();

    internal sealed class GrpcModel
    {
        public string RootNamespace { get; init; } = "";
        public string ModuleNamespace { get; init; } = "";
        public string ModuleName { get; init; } = "";
        public string EntityName { get; init; } = "";
        public string EntityNameLower { get; init; } = "";
        public string EntityPlural { get; init; } = "";
        public string ProtoFile { get; init; } = "";
        public string ProtoPackage { get; init; } = "";
        public string? RequiredPermission { get; init; }
        public string AdminRole { get; init; } = "";
        public string GrpcNamespace => ModuleNamespace + ".Presentation.Grpc";
    }

    private void Write(string template, GrpcModel model, string path, string display, List<string> written)
    {
        if (File.Exists(path))
        {
            AnsiConsole.MarkupLine("  [yellow]•[/] [grey]{0}[/] [yellow](exists, skipped)[/]", Markup.Escape(display));
            return;
        }

        _templates.RenderToFile(template, model, path);
        written.Add(display);
    }

    // Applies a pure text edit; true when the file changed (and was written, unless --dry-run).
    private static bool Edit(string path, Func<string, string> edit, List<string> written, ModuleDiscovery.AppInventory app)
    {
        if (!File.Exists(path))
            return false;
        var before = File.ReadAllText(path);
        var after = edit(before);
        if (after == before)
            return false;
        Ux.WriteFile(path, after);
        written.Add(Path.GetRelativePath(app.SolutionDir, path).Replace('\\', '/') + " (updated)");
        return true;
    }

    private static string Relative(ModuleDiscovery.AppInventory app, string dir, string file)
        => Path.GetRelativePath(app.SolutionDir, Path.Combine(dir, file)).Replace('\\', '/');

    [GeneratedRegex("^[A-Z][A-Za-z0-9]*$")]
    private static partial Regex PascalCase();

    [GeneratedRegex("^\\s*Permissions\\(\"([^\"]+)\"\\);", RegexOptions.Multiline)]
    private static partial Regex PermissionCall();

    [GeneratedRegex("(?<=[a-z0-9])([A-Z])")]
    private static partial Regex SnakeBoundary();
}
