<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Cobytelabs.Modulus.Core" Version="1.2.0" />
    <PackageReference Include="Cobytelabs.Modulus.Mediator" Version="1.2.0" />
    <PackageReference Include="Cobytelabs.Modulus.EntityFrameworkCore" Version="1.2.0" />
    <PackageReference Include="Cobytelabs.Modulus.Events" Version="1.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../ProcureFlow.Modules.Approval.Domain/ProcureFlow.Modules.Approval.Domain.csproj" />
    <ProjectReference Include="../../../Shared/ProcureFlow.Shared.Application/ProcureFlow.Shared.Application.csproj" />
  </ItemGroup>

</Project>
