<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="../../core/Modulus.Core/Modulus.Core.csproj" />
    <ProjectReference Include="../../core/Modulus.AspNetCore/Modulus.AspNetCore.csproj" />
    <ProjectReference Include="../../messaging/Modulus.Mediator/Modulus.Mediator.csproj" />
    <PackageReference Include="OpenTelemetry" />
    <PackageReference Include="OpenTelemetry.Api" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" />
  </ItemGroup>

</Project>
