<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.9" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.12.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ModulusSample.Shared.Application\ModulusSample.Shared.Application.csproj" />
    <ProjectReference Include="..\ModulusSample.Shared.Presentation\ModulusSample.Shared.Presentation.csproj" />
  </ItemGroup>

</Project>
