namespace Modulus.Cli.Services;

/// <summary>
/// The framework NuGet package version that generated apps reference.
/// Bump this (and the matching entry in build/Modulus.Packaging.props)
/// when releasing a new framework version.
/// </summary>
internal static class FrameworkVersion
{
    // Keep in sync with <VersionPrefix> in build/Modulus.Packaging.props —
    // generated apps pin Cobytelabs.Modulus.* packages at this version.
    public const string Current = "1.4.0";
}

/// <summary>
/// Provider metadata shared by <see cref="AppModel"/> and <see cref="ModuleModel"/>,
/// so the EF Core package / extension method / connection-string logic is not duplicated.
/// </summary>
internal static class DbProviderInfo
{
    // Source of truth: Directory.Packages.props (EF Core group).
    // Keep Package()/Version() below in sync when bumping EF provider versions.
    public static string Package(string provider) => provider switch
    {
        "SqlServer" => "Microsoft.EntityFrameworkCore.SqlServer",
        "PostgreSQL" => "Npgsql.EntityFrameworkCore.PostgreSQL",
        "MySQL" => "MySql.EntityFrameworkCore",
        _ => "Microsoft.EntityFrameworkCore.Sqlite",
    };

    public static string Version(string provider) => provider switch
    {
        "SqlServer" => "10.0.9",
        "PostgreSQL" => "10.0.2",
        "MySQL" => "10.0.7",
        _ => "10.0.9",
    };

    public static string UseMethod(string provider) => provider switch
    {
        "SqlServer" => "UseSqlServer",
        "PostgreSQL" => "UseNpgsql",
        "MySQL" => "UseMySql",
        _ => "UseSqlite",
    };

    /// <summary>
    /// A per-module connection string (e.g. <c>Data Source=catalog.db</c>).
    /// Each module gets its own database so <c>EnsureCreated</c> works per-context.
    /// </summary>
    public static string ConnectionString(string provider, string moduleName)
    {
        var db = moduleName.ToLowerInvariant();
        return provider switch
        {
            "SqlServer" => $"Server=localhost;Database=modulus_{db};Trusted_Connection=True;TrustServerCertificate=True",
            "PostgreSQL" => $"Host=localhost;Database=modulus_{db};Username=postgres;Password=postgres",
            "MySQL" => $"Server=localhost;Database=modulus_{db};User=root;Password=root",
            _ => $"Data Source={db}.db",
        };
    }

    /// <summary>
    /// The dbsh provider id for an EF provider name (dbsh uses lower-case
    /// ids: sqlite, sqlserver, postgresql, mysql, ...).
    /// </summary>
    public static string DbshProvider(string provider) => provider switch
    {
        "SqlServer" => "sqlserver",
        "PostgreSQL" => "postgresql",
        "MySQL" => "mysql",
        _ => "sqlite",
    };
}

/// <summary>
/// Model passed to Scriban templates when generating an application.
/// </summary>
internal sealed class AppModel
{
    /// <summary>Full root namespace, e.g. "MyCompany.MyApp".</summary>
    public string RootNamespace { get; set; } = "";

    /// <summary>Framework NuGet package version stamped into generated csproj files.</summary>
    public string FrameworkVersion => Services.FrameworkVersion.Current;

    /// <summary>Last segment of the namespace, e.g. "MyApp".</summary>
    public string AppName { get; set; } = "";

    /// <summary>When true, skip generating the example module.</summary>
    public bool NoExample { get; set; }

    /// <summary>Name of the example module generated by default.</summary>
    public string ExampleModule { get; set; } = "Catalog";

    /// <summary>Lower-cased example module name, used for route prefixes.</summary>
    public string ExampleModuleLower => ExampleModule.ToLowerInvariant();

    /// <summary>Aggregate entity generated inside the example module.</summary>
    public string ExampleEntity { get; set; } = "Product";

    /// <summary>"SQLite", "SqlServer", "PostgreSQL", or "MySQL".</summary>
    public string DbProvider { get; set; } = "SQLite";

    /// <summary>
    /// Path to a local NuGet feed containing the Cobytelabs.Modulus.* packages
    /// (from <c>--package-source</c>). When set, the generated NuGet.config
    /// registers it as an ACTIVE <c>modulus-local</c> source; when null only
    /// nuget.org is configured and a restore of the framework packages will
    /// fail until one is wired (flagged in the command's next-steps output).
    /// </summary>
    public string? LocalPackageSource { get; set; }

    /// <summary>
    /// Migration engine for generated modules: "efcore" (default, EF Core
    /// migrations) or "dbsh" (SQL-first migrations managed by the external
    /// dbsh tool). Propagates to every module the app generates.
    /// </summary>
    public string MigrationEngine { get; set; } = "efcore";

    /// <summary>True when modules manage their schema with dbsh SQL migrations.</summary>
    public bool UseDbsh => MigrationEngine == "dbsh";

    /// <summary>
    /// UI modules to include in the generated app (lower-case IDs: identity, permissions, tenancy, users, settings, auditlogging, notifications, files).
    /// </summary>
    public IReadOnlyList<string> UiModules { get; set; } = [];

    /// <summary>API only, or a web app that also exposes the API (<c>--kind</c>).</summary>
    public AppKind Kind { get; set; } = AppKind.Api;

    /// <summary>The kind as written into the host csproj (<c>&lt;ModulusAppKind&gt;</c>).</summary>
    public string KindName => Kind.Name();

    /// <summary>True for a web app: it gets the UI foundation (and the theme), whatever feature modules are chosen.</summary>
    public bool UseUi => Kind is AppKind.WebApp or AppKind.WebAppApi;

    /// <summary>
    /// True when the project rendered from the host templates (the API project) itself serves the UI: the single-project
    /// web kinds only. The webapp+api split's API host never does — its pages live in the separate Web project — so it
    /// renders with <c>use_ui</c> off: no Razor Pages, no <c>AddModulusSmartAuth</c> (bearer is the default scheme), no
    /// authorization-code flow (there is no login page on the API to sign users in through).
    /// </summary>
    public bool UiInApiHost => UseUi && Kind != AppKind.WebAppApi;

    /// <summary>True when the app exposes API endpoints to external callers (api and webapp+api kinds). False for webapp kind (internal IMediator only).</summary>
    public bool ExposeApi => Kind is AppKind.Api or AppKind.WebAppApi;

    /// <summary>Install the Tabler theme next to the UI modules (default; <c>--no-theme</c> turns it off).</summary>
    public bool UseTablerTheme { get; set; }

    /// <summary>
    /// The UI host project's namespace (<c>{Root}.Web</c> for the webapp+api split, <c>{Root}.Api</c> otherwise).
    /// Set by <c>GenerateAll</c>; defaults so every template that renders <c>{{ ui_namespace }}</c> (the example
    /// <c>ModuleApiClient</c> when <c>modulus app</c> generates a Web project) gets a valid namespace.
    /// </summary>
    public string UiNamespace
    {
        get => string.IsNullOrEmpty(_uiNamespace) ? $"{RootNamespace}.Api" : _uiNamespace;
        set => _uiNamespace = value;
    }

    private string? _uiNamespace;

    /// <summary>
    /// Auth provider key: "none" (default), "openiddict", or one of the six
    /// external IdPs ("auth0", "authentik", "azuread", "duende", "keycloak", "okta").
    /// </summary>
    public string Auth { get; set; } = "none";

    /// <summary>True when any auth provider is selected.</summary>
    public bool UseAuth => Auth != "none";

    /// <summary>True when the local OpenIddict token server is selected.</summary>
    public bool UseOpenIddict => Auth == "openiddict";

    /// <summary>Lower-cased app name (the seeded development administrator is <c>admin@{name}.local</c>).</summary>
    public string AppNameLower => AppName.ToLowerInvariant();

    /// <summary>
    /// Namespace of the generated identity backend module (<c>{Root}.Modules.Identity</c>), generated with
    /// <c>--auth openiddict</c>: a local token server needs users, so it comes with an identity database.
    /// </summary>
    public string IdentityNamespace => $"{RootNamespace}.Modules.Identity";

    /// <summary>Connection string for the identity database (its own database, like every module).</summary>
    public string IdentityConnectionString => DbProviderInfo.ConnectionString(DbProvider, "Identity");

    /// <summary>True when an external identity provider is selected.</summary>
    public bool UseExternalProvider => AuthProviders.IsExternalProvider(Auth);

    /// <summary>Display name of the selected external provider (empty when N/A).</summary>
    public string ExternalProviderName =>
        UseExternalProvider ? AuthProviders.Find(Auth)?.DisplayName ?? "" : "";

    /// <summary>Extension method name, e.g. "AddKeycloak" (empty when N/A).</summary>
    public string ExternalProviderAddMethod =>
        UseExternalProvider ? AuthProviders.Find(Auth)?.AddMethod ?? "" : "";

    /// <summary>C# namespace for the external provider's Add method (empty when N/A).</summary>
    public string ExternalProviderNamespace =>
        UseExternalProvider ? AuthProviders.Find(Auth)?.Namespace ?? "" : "";

    /// <summary>Config key path, e.g. "Identity:ExternalProviders:Keycloak" (empty when N/A).</summary>
    public string ExternalProviderConfigKey =>
        UseExternalProvider ? AuthProviders.Find(Auth)?.ConfigKey ?? "" : "";

    /// <summary>JSON block for the Identity config section in appsettings.json (empty when no auth).</summary>
    public string IdentityConfigJson =>
        UseAuth ? AuthProviders.Find(Auth)?.ConfigJson ?? "" : "";

    /// <summary>EF Core DbContextOptions extension method name.</summary>
    public string UseDbMethod => DbProviderInfo.UseMethod(DbProvider);

    /// <summary>EF Core package name for the provider.</summary>
    public string EfProviderPackage => DbProviderInfo.Package(DbProvider);

    /// <summary>EF Core package version for the provider.</summary>
    public string EfProviderVersion => DbProviderInfo.Version(DbProvider);


    /// <summary>
    /// Per-app User Secrets id, stamped into the host .csproj so
    /// <c>dotnet user-secrets</c> and the Development configuration provider have a
    /// stable store to keep secrets out of committed appsettings files.
    /// </summary>
    public string UserSecretsId { get; set; } = Guid.NewGuid().ToString();

    /// <summary>Connection string for the example module (per-module DB).</summary>
    public string ConnectionString =>
        DbProviderInfo.ConnectionString(DbProvider, ExampleModule);

    /// <summary>
    /// REST route for the example entity (e.g. "products"). Must match the
    /// module generator's route (<c>CodeGen.Pluralize(entity).ToLowerInvariant()</c>)
    /// so the generated integration test hits the real endpoint.
    /// </summary>
    public string ExampleRoute =>
        CodeGen.Pluralize(ExampleEntity).ToLowerInvariant();

    // ── Module-level aliases ───────────────────────────────────────
    // The ui/* module templates (CrudIndexPageModel.Http, ModuleApiClient, ...)
    // are rendered against ModuleModel by `generate-crud`, with variables like
    // `module_name` / `module_namespace` / `entity_name` / `route_name`. At
    // `modulus app` time the app model renders the same templates for the
    // example module — these aliases supply the same names.

    /// <summary>Alias of <see cref="ExampleModule"/>: the module-level template variable name.</summary>
    public string ModuleName => ExampleModule;

    /// <summary>Lower-cased module name for route prefixes.</summary>
    public string ModuleNameLower => ExampleModuleLower;

    /// <summary>The example module's root namespace (e.g. "MyApp.Modules.Catalog").</summary>
    public string ModuleNamespace => $"{RootNamespace}.Modules.{ExampleModule}";

    /// <summary>Alias of <see cref="ExampleEntity"/>.</summary>
    public string EntityName => ExampleEntity;

    /// <summary>Lower-cased example entity name.</summary>
    public string EntityNameLower => ExampleEntity.ToLowerInvariant();

    /// <summary>Alias of <see cref="ExampleRoute"/>.</summary>
    public string RouteName => ExampleRoute;

    /// <summary>
    /// The permission that guards the example entity's API (and its admin page), when the app has the identity backend whose
    /// <c>Admin</c> role holds it; null otherwise. The same <c>{module}:{route}:manage</c> a later <c>generate-crud</c> would pick.
    /// </summary>
    public string? ExamplePermission =>
        UseOpenIddict && !NoExample ? UiAccessGates.CrudPermission(ExampleModule, ExampleRoute) : null;

    /// <summary>
    /// True when the app serves the authorization-code flow with PKCE (<c>/connect/authorize</c>): a web app with the local token
    /// server whose API project itself hosts the login page (the Identity UI), because that flow signs the user in through the app's
    /// own page. The webapp+api split's API has no page to sign in with — its Web project signs users in over the password grant —
    /// so there the code flow stays off and its clients use the password grant while it is on, then refresh tokens.
    /// </summary>
    public bool UseCodeFlow => UseOpenIddict && UiInApiHost;

    /// <summary>Redirect URIs the seeded first-party client is registered with in Development: a native app's custom scheme and a local SPA dev server.</summary>
    public IReadOnlyList<string> DevRedirectUris => [$"{AppNameLower}://callback", "http://localhost:5173/callback"];

    /// <summary>What the example permission's registry entry says.</summary>
    public string ExamplePermissionDescription =>
        UiAccessGates.CrudPermissionDescription(CodeGen.Pluralize(ExampleEntity));

    /// <summary>The role that holds the example permission (the one the identity backend seeds the first administrator into).</summary>
    public string AdminRole => UiAccessGates.AdminRole;

    // ── Message Broker Configuration ────────────────────────────────
    /// <summary>Message broker: "none", "rabbitmq", or "kafka".</summary>
    public string MessageBroker { get; set; } = "none";

    /// <summary>True when any message broker is selected.</summary>
    public bool UseMessageBroker => MessageBroker != "none";

    /// <summary>True when RabbitMQ is selected.</summary>
    public bool UseRabbitMq => MessageBroker == "rabbitmq";

    /// <summary>True when Kafka is selected.</summary>
    public bool UseKafka => MessageBroker == "kafka";

    // ── Caching Configuration ───────────────────────────────────────
    /// <summary>Caching provider: "inmemory" or "redis".</summary>
    public string CachingProvider { get; set; } = "inmemory";

    /// <summary>True when Redis caching is selected.</summary>
    public bool UseRedisCache => CachingProvider == "redis";

    // ── Storage Configuration ───────────────────────────────────────
    /// <summary>Storage provider: "local", "s3", or "azureblobs".</summary>
    public string StorageProvider { get; set; } = "local";

    /// <summary>True when S3 storage is selected.</summary>
    public bool UseS3Storage => StorageProvider == "s3";

    /// <summary>True when Azure Blob storage is selected.</summary>
    public bool UseAzureStorage => StorageProvider == "azureblobs";

    // ── SignalR Configuration ───────────────────────────────────────
    /// <summary>SignalR backplane: "none", "redis", or "azure".</summary>
    public string SignalRBackplane { get; set; } = "none";

    /// <summary>True when Redis SignalR backplane is selected.</summary>
    public bool UseRedisSignalR => SignalRBackplane == "redis";

    /// <summary>True when Azure SignalR backplane is selected.</summary>
    public bool UseAzureSignalR => SignalRBackplane == "azure";

    // ── Production Hardening Features ───────────────────────────────
    /// <summary>Enable API versioning.</summary>
    public bool EnableApiVersioning { get; set; } = true;

    /// <summary>Enable rate limiting.</summary>
    public bool EnableRateLimiting { get; set; } = true;

    /// <summary>Enable health checks.</summary>
    public bool EnableHealthChecks { get; set; } = true;

    /// <summary>Enable feature flags.</summary>
    public bool EnableFeatureFlags { get; set; } = false;

    /// <summary>Enable CORS.</summary>
    public bool EnableCors { get; set; } = true;

    /// <summary>Enable security headers.</summary>
    public bool EnableSecurityHeaders { get; set; } = true;

    /// <summary>Enable HTTP idempotency.</summary>
    public bool EnableIdempotency { get; set; } = false;

    /// <summary>Enable request correlation.</summary>
    public bool EnableCorrelation { get; set; } = true;

    /// <summary>Enable secrets guard.</summary>
    public bool EnableSecretsGuard { get; set; } = true;

    /// <summary>Enable personal data protection.</summary>
    public bool EnablePersonalDataProtection { get; set; } = false;
}

/// <summary>
/// Model for generating a module project.
/// </summary>
/// <remarks>
/// The 4-layer (FoodDelivery-style) layout produces four projects per module:
/// <c>Domain</c>, <c>Application</c>, <c>Infrastructure</c>, <c>Presentation</c>.
/// DTOs live under <c>Application/Dtos</c> and integration events under
/// <c>Application/IntegrationEvents</c> (no separate Contracts / IntegrationEvents
/// projects). There is no per-module Tests project; tests live at the solution
/// root.
/// </remarks>
internal sealed class ModuleModel
{
    public string RootNamespace { get; set; } = "";
    public string ModuleName { get; set; } = "";        // "Catalog"
    public string ModuleNamespace { get; set; } = "";   // "MyApp.Modules.Catalog"

    /// <summary>Framework NuGet package version stamped into generated csproj files.</summary>
    public string FrameworkVersion => Services.FrameworkVersion.Current;

    // ── Database provider ──────────────────────────────────────────
    /// <summary>"SQLite", "SqlServer", "PostgreSQL", or "MySQL".</summary>
    public string DbProvider { get; set; } = "SQLite";

    /// <summary>EF Core DbContextOptions extension method name.</summary>
    public string UseDbMethod => DbProviderInfo.UseMethod(DbProvider);

    /// <summary>EF Core package name for the provider.</summary>
    public string EfProviderPackage => DbProviderInfo.Package(DbProvider);

    /// <summary>EF Core package version for the provider.</summary>
    public string EfProviderVersion => DbProviderInfo.Version(DbProvider);

    /// <summary>Per-module connection string (fallback if not in appsettings).</summary>
    public string ConnectionString =>
        DbProviderInfo.ConnectionString(DbProvider, ModuleName);

    // ── Migration engine ───────────────────────────────────────────
    /// <summary>
    /// Migration engine: "efcore" (default, EF Core migrations authored in
    /// Infrastructure/Migrations) or "dbsh" (SQL-first migrations under
    /// Infrastructure/Database, applied by the external dbsh tool).
    /// </summary>
    public string MigrationEngine { get; set; } = "efcore";

    /// <summary>True when the module's schema is managed by dbsh SQL migrations.</summary>
    public bool UseDbsh => MigrationEngine == "dbsh";

    /// <summary>dbsh provider id for the module's database ("sqlite", ...).</summary>
    public string DbshProvider => DbProviderInfo.DbshProvider(DbProvider);

    /// <summary>
    /// Environment variable dbsh expands for the module's connection string
    /// (e.g. <c>CATALOG_CONNECTION</c> — referenced as <c>${CATALOG_CONNECTION}</c>
    /// in the generated migration.json so no secret is ever committed).
    /// </summary>
    public string DbshConnectionEnvVar => $"{ModuleName.ToUpperInvariant()}_CONNECTION";

    /// <summary>
    /// The <c>${MODULE_CONNECTION}</c> expansion token for the generated
    /// migration.json (dbsh expands <c>${VAR}</c> tokens from the environment).
    /// Pre-built as one value because Scriban would treat a literal <c>{</c>
    /// before a <c>{{ }}</c> block as part of the tag delimiter.
    /// </summary>
    public string DbshConnectionStringToken => "${" + DbshConnectionEnvVar + "}";

    // ── Layer project names (4-layer layout) ──────────────────────
    public string DomainProject => $"{ModuleNamespace}.Domain";
    public string ApplicationProject => $"{ModuleNamespace}.Application";
    public string InfrastructureProject => $"{ModuleNamespace}.Infrastructure";
    public string PresentationProject => $"{ModuleNamespace}.Presentation";

    // Lower-cased module name, used for table prefix + integration event type strings.
    public string ModuleNameLower => ModuleName.ToLowerInvariant();

    /// <summary>
    /// The host API project's root namespace (e.g. <c>MyApp.Api</c>). Used by
    /// <c>generate-crud --with-ui</c> for the companion Razor Pages + the
    /// <c>CustomUiModule</c> nav sidecar, which live in the Api project (Web SDK
    /// compiles <c>Pages/</c> with no csproj changes).
    /// </summary>
    public string ApiNamespace => $"{RootNamespace}.Api";

    /// <summary>
    /// The UI host project's root namespace. For webapp+api kind, this is the Web project
    /// (e.g. <c>MyApp.Web</c>); for other kinds, it defaults to <see cref="ApiNamespace"/>.
    /// Used in generated CRUD page namespaces. Defaults to <see cref="ApiNamespace"/> when unset,
    /// so every template that renders <c>{{ ui_namespace }}</c> gets a valid namespace even on a
    /// path that never chose a UI host.
    /// </summary>
    public string UiNamespace
    {
        get => string.IsNullOrEmpty(_uiNamespace) ? ApiNamespace : _uiNamespace;
        set => _uiNamespace = value;
    }

    private string? _uiNamespace;

    // ── Entity being scaffolded (null when generating a blank module) ──
    // Scriban treats "" as truthy, so blank modules must leave these null.
    public string? EntityName { get; set; }       // "Product"
    public string? EntityNameLower { get; set; }  // "product"
    public string? RouteName { get; set; }        // "products"

    /// <summary>
    /// True when the entity implements <c>IHasExtraProperties</c> and its create command carries the extension values,
    /// so the generated create form can render <c>&lt;m-fields&gt;</c> and pass them on. False for a CRUD set generated
    /// before that existed (files are never overwritten), where the form would only collect data that is dropped.
    /// </summary>
    public bool HasExtraFields { get; set; }

    /// <summary>
    /// True when the page also gets an edit modal: the update command carries the extension values (so an edit can
    /// save them) and the host has a theme that provides the modal container. The edit form reads the stored values
    /// through a dedicated <c>Get{Entity}ForEditQuery</c>, not the API DTO.
    /// </summary>
    public bool HasEditForm { get; set; }

    /// <summary>
    /// True in a web app: the API exposes the entity's extension fields, filtered through the same registry and
    /// per-field permissions as the form (<c>EntityApiFields</c>), so external clients (mobile, desktop, other systems)
    /// can read and write them. The DTO carries the bag, the endpoints validate and filter it, and the Presentation
    /// project references <c>Modulus.UI.Core</c> for the registry. False for an API-only app (there is no registry to
    /// filter with, so the bag is never exposed) and for a CRUD set generated before extension fields existed.
    /// </summary>
    public bool HasApiExtraFields { get; set; }

    /// <summary>
    /// The permission (e.g. <c>catalog:products:manage</c>) the generated API endpoints and admin page require, or null when the host
    /// has no identity backend whose <c>Admin</c> role could hold it (then they are as open as the rest of that host). See
    /// <see cref="UiAccessGates.CrudPermission"/>.
    /// </summary>
    public string? RequiredPermission { get; set; }

    /// <summary>Pascal-case plural of <see cref="EntityName"/> (e.g. "Products").</summary>
    public string? EntityPlural => string.IsNullOrEmpty(EntityName)
        ? null
        : CodeGen.Pluralize(EntityName);
}

/// <summary>
/// Model for generating a single command or query handler within an existing module,
/// without creating a full CRUD set.
/// </summary>
internal sealed class FeatureModel
{
    public string RootNamespace { get; set; } = "";
    public string ModuleName { get; set; } = "";        // "Catalog"
    public string ModuleNamespace { get; set; } = "";   // "MyApp.Modules.Catalog"

    // Feature name: "CreateOrder", "PublishEvent", etc.
    public string FeatureName { get; set; } = "";

    // Lowercase first letter: "createOrder", "publishEvent"
    public string FeatureNameLower { get; set; } = "";

    // 4-layer project names
    public string ApplicationProject => $"{ModuleNamespace}.Application";
    public string InfrastructureProject => $"{ModuleNamespace}.Infrastructure";

    public string ModuleNameLower => ModuleName.ToLowerInvariant();
}
