namespace Modulus.Cli.Services;

/// <summary>
/// Provider metadata shared by <see cref="AppModel"/> and <see cref="ModuleModel"/>,
/// so the EF Core package / extension method / connection-string logic is not duplicated.
/// </summary>
internal static class DbProviderInfo
{
    public static string Package(string provider) => provider switch
    {
        "SqlServer" => "Microsoft.EntityFrameworkCore.SqlServer",
        "PostgreSQL" => "Npgsql.EntityFrameworkCore.PostgreSQL",
        "MySQL" => "MySql.EntityFrameworkCore",
        _ => "Microsoft.EntityFrameworkCore.Sqlite",
    };

    public static string Version(string provider) => provider switch
    {
        "SqlServer" => "10.0.9",
        "PostgreSQL" => "10.0.2",
        "MySQL" => "10.0.7",
        _ => "10.0.9",
    };

    public static string UseMethod(string provider) => provider switch
    {
        "SqlServer" => "UseSqlServer",
        "PostgreSQL" => "UseNpgsql",
        "MySQL" => "UseMySql",
        _ => "UseSqlite",
    };

    /// <summary>
    /// A per-module connection string (e.g. <c>Data Source=catalog.db</c>).
    /// Each module gets its own database so <c>EnsureCreated</c> works per-context.
    /// </summary>
    public static string ConnectionString(string provider, string moduleName)
    {
        var db = moduleName.ToLowerInvariant();
        return provider switch
        {
            "SqlServer" => $"Server=localhost;Database=modulus_{db};Trusted_Connection=True;TrustServerCertificate=True",
            "PostgreSQL" => $"Host=localhost;Database=modulus_{db};Username=postgres;Password=postgres",
            "MySQL" => $"Server=localhost;Database=modulus_{db};User=root;Password=root",
            _ => $"Data Source={db}.db",
        };
    }
}

/// <summary>
/// Model passed to Scriban templates when generating an application.
/// </summary>
internal sealed class AppModel
{
    /// <summary>Full root namespace, e.g. "MyCompany.MyApp".</summary>
    public string RootNamespace { get; set; } = "";

    /// <summary>Last segment of the namespace, e.g. "MyApp".</summary>
    public string AppName { get; set; } = "";

    /// <summary>When true, skip generating the example module.</summary>
    public bool NoExample { get; set; }

    /// <summary>Name of the example module generated by default.</summary>
    public string ExampleModule { get; set; } = "Catalog";

    /// <summary>Aggregate entity generated inside the example module.</summary>
    public string ExampleEntity { get; set; } = "Product";

    /// <summary>"SQLite", "SqlServer", "PostgreSQL", or "MySQL".</summary>
    public string DbProvider { get; set; } = "SQLite";

    /// <summary>EF Core DbContextOptions extension method name.</summary>
    public string UseDbMethod => DbProviderInfo.UseMethod(DbProvider);

    /// <summary>EF Core package name for the provider.</summary>
    public string EfProviderPackage => DbProviderInfo.Package(DbProvider);

    /// <summary>EF Core package version for the provider.</summary>
    public string EfProviderVersion => DbProviderInfo.Version(DbProvider);

    /// <summary>
    /// Per-app User Secrets id, stamped into the host .csproj so
    /// <c>dotnet user-secrets</c> and the Development configuration provider have a
    /// stable store to keep secrets out of committed appsettings files.
    /// </summary>
    public string UserSecretsId { get; set; } = Guid.NewGuid().ToString();

    /// <summary>Connection string for the example module (per-module DB).</summary>
    public string ConnectionString =>
        DbProviderInfo.ConnectionString(DbProvider, ExampleModule);

    /// <summary>
    /// REST route for the example entity (e.g. "products"). Must match the
    /// module generator's route (<c>ToPlural(entity).ToLowerInvariant()</c>) so
    /// the generated integration test hits the real endpoint.
    /// </summary>
    public string ExampleRoute =>
        (ExampleEntity.EndsWith('s') ? ExampleEntity + "es" : ExampleEntity + "s")
        .ToLowerInvariant();
}

/// <summary>
/// Model for generating a module project.
/// </summary>
/// <remarks>
/// The 4-layer (FoodDelivery-style) layout produces four projects per module:
/// <c>Domain</c>, <c>Application</c>, <c>Infrastructure</c>, <c>Presentation</c>.
/// DTOs live under <c>Application/Dtos</c> and integration events under
/// <c>Application/IntegrationEvents</c> (no separate Contracts / IntegrationEvents
/// projects). There is no per-module Tests project; tests live at the solution
/// root.
/// </remarks>
internal sealed class ModuleModel
{
    public string RootNamespace { get; set; } = "";
    public string ModuleName { get; set; } = "";        // "Catalog"
    public string ModuleNamespace { get; set; } = "";   // "MyApp.Modules.Catalog"

    // ── Database provider ──────────────────────────────────────────
    /// <summary>"SQLite", "SqlServer", "PostgreSQL", or "MySQL".</summary>
    public string DbProvider { get; set; } = "SQLite";

    /// <summary>EF Core DbContextOptions extension method name.</summary>
    public string UseDbMethod => DbProviderInfo.UseMethod(DbProvider);

    /// <summary>EF Core package name for the provider.</summary>
    public string EfProviderPackage => DbProviderInfo.Package(DbProvider);

    /// <summary>EF Core package version for the provider.</summary>
    public string EfProviderVersion => DbProviderInfo.Version(DbProvider);

    /// <summary>Per-module connection string (fallback if not in appsettings).</summary>
    public string ConnectionString =>
        DbProviderInfo.ConnectionString(DbProvider, ModuleName);

    // ── Layer project names (4-layer layout) ──────────────────────
    public string DomainProject => $"{ModuleNamespace}.Domain";
    public string ApplicationProject => $"{ModuleNamespace}.Application";
    public string InfrastructureProject => $"{ModuleNamespace}.Infrastructure";
    public string PresentationProject => $"{ModuleNamespace}.Presentation";

    // Lower-cased module name, used for table prefix + integration event type strings.
    public string ModuleNameLower => ModuleName.ToLowerInvariant();

    // ── Entity being scaffolded (null when generating a blank module) ──
    // Scriban treats "" as truthy, so blank modules must leave these null.
    public string? EntityName { get; set; }       // "Product"
    public string? EntityNameLower { get; set; }  // "product"
    public string? RouteName { get; set; }        // "products"

    /// <summary>Pascal-case plural of <see cref="EntityName"/> (e.g. "Products").</summary>
    public string? EntityPlural => string.IsNullOrEmpty(EntityName)
        ? null
        : Pluralize(EntityName);

    private static string Pluralize(string s)
    {
        if (string.IsNullOrEmpty(s)) return s;

        // Words already ending with 's', 'x', 'z', 'ch', 'sh' → add 'es'
        if (s.EndsWith("ch", StringComparison.OrdinalIgnoreCase)
         || s.EndsWith("sh", StringComparison.OrdinalIgnoreCase)
         || s.EndsWith('x')
         || s.EndsWith('z'))
            return s + "es";

        // Words ending with consonant + 'y' → drop 'y', add 'ies'
        if (s.Length > 1 && s.EndsWith('y')
            && !"aeiouAEIOU".Contains(s[^2]))
            return s[..^1] + "ies";

        // Words ending with 's' (but not 'ss') → already plural, just append 'es'
        // e.g. "Status" → "Statuses", "Bus" → "Buses"
        if (s.EndsWith('s'))
            return s + "es";

        // Default: just add 's'
        return s + "s";
    }
}
