namespace Modulus.Cli.Services;

/// <summary>
/// The framework NuGet package version that generated apps reference.
/// Bump this (and the matching entry in build/Modulus.Packaging.props)
/// when releasing a new framework version.
/// </summary>
internal static class FrameworkVersion
{
    // Keep in sync with <VersionPrefix> in build/Modulus.Packaging.props —
    // generated apps pin Cobytelabs.Modulus.* packages at this version.
    public const string Current = "1.2.0";
}

/// <summary>
/// Provider metadata shared by <see cref="AppModel"/> and <see cref="ModuleModel"/>,
/// so the EF Core package / extension method / connection-string logic is not duplicated.
/// </summary>
internal static class DbProviderInfo
{
    public static string Package(string provider) => provider switch
    {
        "SqlServer" => "Microsoft.EntityFrameworkCore.SqlServer",
        "PostgreSQL" => "Npgsql.EntityFrameworkCore.PostgreSQL",
        "MySQL" => "MySql.EntityFrameworkCore",
        _ => "Microsoft.EntityFrameworkCore.Sqlite",
    };

    public static string Version(string provider) => provider switch
    {
        "SqlServer" => "10.0.9",
        "PostgreSQL" => "10.0.2",
        "MySQL" => "10.0.7",
        _ => "10.0.9",
    };

    public static string UseMethod(string provider) => provider switch
    {
        "SqlServer" => "UseSqlServer",
        "PostgreSQL" => "UseNpgsql",
        "MySQL" => "UseMySql",
        _ => "UseSqlite",
    };

    /// <summary>
    /// A per-module connection string (e.g. <c>Data Source=catalog.db</c>).
    /// Each module gets its own database so <c>EnsureCreated</c> works per-context.
    /// </summary>
    public static string ConnectionString(string provider, string moduleName)
    {
        var db = moduleName.ToLowerInvariant();
        return provider switch
        {
            "SqlServer" => $"Server=localhost;Database=modulus_{db};Trusted_Connection=True;TrustServerCertificate=True",
            "PostgreSQL" => $"Host=localhost;Database=modulus_{db};Username=postgres;Password=postgres",
            "MySQL" => $"Server=localhost;Database=modulus_{db};User=root;Password=root",
            _ => $"Data Source={db}.db",
        };
    }
}

/// <summary>
/// Model passed to Scriban templates when generating an application.
/// </summary>
internal sealed class AppModel
{
    /// <summary>Full root namespace, e.g. "MyCompany.MyApp".</summary>
    public string RootNamespace { get; set; } = "";

    /// <summary>Framework NuGet package version stamped into generated csproj files.</summary>
    public string FrameworkVersion => Services.FrameworkVersion.Current;

    /// <summary>Last segment of the namespace, e.g. "MyApp".</summary>
    public string AppName { get; set; } = "";

    /// <summary>When true, skip generating the example module.</summary>
    public bool NoExample { get; set; }

    /// <summary>Name of the example module generated by default.</summary>
    public string ExampleModule { get; set; } = "Catalog";

    /// <summary>Lower-cased example module name, used for route prefixes.</summary>
    public string ExampleModuleLower => ExampleModule.ToLowerInvariant();

    /// <summary>Aggregate entity generated inside the example module.</summary>
    public string ExampleEntity { get; set; } = "Product";

    /// <summary>"SQLite", "SqlServer", "PostgreSQL", or "MySQL".</summary>
    public string DbProvider { get; set; } = "SQLite";

    /// <summary>
    /// Path to a local NuGet feed containing the Cobytelabs.Modulus.* packages
    /// (from <c>--package-source</c>). When set, the generated NuGet.config
    /// registers it as an ACTIVE <c>modulus-local</c> source; when null only
    /// nuget.org is configured and a restore of the framework packages will
    /// fail until one is wired (flagged in the command's next-steps output).
    /// </summary>
    public string? LocalPackageSource { get; set; }

    /// <summary>
    /// Auth provider key: "none" (default), "openiddict", or one of the six
    /// external IdPs ("auth0", "authentik", "azuread", "duende", "keycloak", "okta").
    /// </summary>
    public string Auth { get; set; } = "none";

    /// <summary>True when any auth provider is selected.</summary>
    public bool UseAuth => Auth != "none";

    /// <summary>True when the local OpenIddict token server is selected.</summary>
    public bool UseOpenIddict => Auth == "openiddict";

    /// <summary>True when an external identity provider is selected.</summary>
    public bool UseExternalProvider => AuthProviders.IsExternalProvider(Auth);

    /// <summary>Display name of the selected external provider (empty when N/A).</summary>
    public string ExternalProviderName =>
        UseExternalProvider ? AuthProviders.Find(Auth)?.DisplayName ?? "" : "";

    /// <summary>Extension method name, e.g. "AddKeycloak" (empty when N/A).</summary>
    public string ExternalProviderAddMethod =>
        UseExternalProvider ? AuthProviders.Find(Auth)?.AddMethod ?? "" : "";

    /// <summary>C# namespace for the external provider's Add method (empty when N/A).</summary>
    public string ExternalProviderNamespace =>
        UseExternalProvider ? AuthProviders.Find(Auth)?.Namespace ?? "" : "";

    /// <summary>Config key path, e.g. "Identity:ExternalProviders:Keycloak" (empty when N/A).</summary>
    public string ExternalProviderConfigKey =>
        UseExternalProvider ? AuthProviders.Find(Auth)?.ConfigKey ?? "" : "";

    /// <summary>JSON block for the Identity config section in appsettings.json (empty when no auth).</summary>
    public string IdentityConfigJson =>
        UseAuth ? AuthProviders.Find(Auth)?.ConfigJson ?? "" : "";

    /// <summary>EF Core DbContextOptions extension method name.</summary>
    public string UseDbMethod => DbProviderInfo.UseMethod(DbProvider);

    /// <summary>EF Core package name for the provider.</summary>
    public string EfProviderPackage => DbProviderInfo.Package(DbProvider);

    /// <summary>EF Core package version for the provider.</summary>
    public string EfProviderVersion => DbProviderInfo.Version(DbProvider);

    // ── Migration Engine ───────────────────────────────────────────
    /// <summary>
    /// Migration engine: "efcore" (default) or "dbsh" (SQL files, managed externally).
    /// </summary>
    public string MigrationEngine { get; set; } = "efcore";

    /// <summary>True when the user chose dbsh as the migration engine.</summary>
    public bool UseDbsh => MigrationEngine == "dbsh";

    /// <summary>
    /// Per-app User Secrets id, stamped into the host .csproj so
    /// <c>dotnet user-secrets</c> and the Development configuration provider have a
    /// stable store to keep secrets out of committed appsettings files.
    /// </summary>
    public string UserSecretsId { get; set; } = Guid.NewGuid().ToString();

    /// <summary>Connection string for the example module (per-module DB).</summary>
    public string ConnectionString =>
        DbProviderInfo.ConnectionString(DbProvider, ExampleModule);

    /// <summary>
    /// REST route for the example entity (e.g. "products"). Must match the
    /// module generator's route (<c>CodeGen.Pluralize(entity).ToLowerInvariant()</c>)
    /// so the generated integration test hits the real endpoint.
    /// </summary>
    public string ExampleRoute =>
        CodeGen.Pluralize(ExampleEntity).ToLowerInvariant();

    // ── Message Broker Configuration ────────────────────────────────
    /// <summary>Message broker: "none", "rabbitmq", or "kafka".</summary>
    public string MessageBroker { get; set; } = "none";

    /// <summary>True when any message broker is selected.</summary>
    public bool UseMessageBroker => MessageBroker != "none";

    /// <summary>True when RabbitMQ is selected.</summary>
    public bool UseRabbitMq => MessageBroker == "rabbitmq";

    /// <summary>True when Kafka is selected.</summary>
    public bool UseKafka => MessageBroker == "kafka";

    // ── Caching Configuration ───────────────────────────────────────
    /// <summary>Caching provider: "inmemory" or "redis".</summary>
    public string CachingProvider { get; set; } = "inmemory";

    /// <summary>True when Redis caching is selected.</summary>
    public bool UseRedisCache => CachingProvider == "redis";

    // ── Storage Configuration ───────────────────────────────────────
    /// <summary>Storage provider: "local", "s3", or "azureblobs".</summary>
    public string StorageProvider { get; set; } = "local";

    /// <summary>True when S3 storage is selected.</summary>
    public bool UseS3Storage => StorageProvider == "s3";

    /// <summary>True when Azure Blob storage is selected.</summary>
    public bool UseAzureStorage => StorageProvider == "azureblobs";

    // ── SignalR Configuration ───────────────────────────────────────
    /// <summary>SignalR backplane: "none", "redis", or "azure".</summary>
    public string SignalRBackplane { get; set; } = "none";

    /// <summary>True when Redis SignalR backplane is selected.</summary>
    public bool UseRedisSignalR => SignalRBackplane == "redis";

    /// <summary>True when Azure SignalR backplane is selected.</summary>
    public bool UseAzureSignalR => SignalRBackplane == "azure";

    // ── Production Hardening Features ───────────────────────────────
    /// <summary>Enable API versioning.</summary>
    public bool EnableApiVersioning { get; set; } = true;

    /// <summary>Enable rate limiting.</summary>
    public bool EnableRateLimiting { get; set; } = true;

    /// <summary>Enable health checks.</summary>
    public bool EnableHealthChecks { get; set; } = true;

    /// <summary>Enable feature flags.</summary>
    public bool EnableFeatureFlags { get; set; } = false;

    /// <summary>Enable CORS.</summary>
    public bool EnableCors { get; set; } = true;

    /// <summary>Enable security headers.</summary>
    public bool EnableSecurityHeaders { get; set; } = true;

    /// <summary>Enable HTTP idempotency.</summary>
    public bool EnableIdempotency { get; set; } = false;

    /// <summary>Enable request correlation.</summary>
    public bool EnableCorrelation { get; set; } = true;

    /// <summary>Enable secrets guard.</summary>
    public bool EnableSecretsGuard { get; set; } = true;

    /// <summary>Enable personal data protection.</summary>
    public bool EnablePersonalDataProtection { get; set; } = false;
}

/// <summary>
/// Model for generating a module project.
/// </summary>
/// <remarks>
/// The 4-layer (FoodDelivery-style) layout produces four projects per module:
/// <c>Domain</c>, <c>Application</c>, <c>Infrastructure</c>, <c>Presentation</c>.
/// DTOs live under <c>Application/Dtos</c> and integration events under
/// <c>Application/IntegrationEvents</c> (no separate Contracts / IntegrationEvents
/// projects). There is no per-module Tests project; tests live at the solution
/// root.
/// </remarks>
internal sealed class ModuleModel
{
    public string RootNamespace { get; set; } = "";
    public string ModuleName { get; set; } = "";        // "Catalog"
    public string ModuleNamespace { get; set; } = "";   // "MyApp.Modules.Catalog"

    /// <summary>Framework NuGet package version stamped into generated csproj files.</summary>
    public string FrameworkVersion => Services.FrameworkVersion.Current;

    // ── Database provider ──────────────────────────────────────────
    /// <summary>"SQLite", "SqlServer", "PostgreSQL", or "MySQL".</summary>
    public string DbProvider { get; set; } = "SQLite";

    // ── Migration engine ──────────────────────────────────────────
    /// <summary>"efcore" (default) or "dbsh" (SQL files, managed externally).</summary>
    public string MigrationEngine { get; set; } = "efcore";

    /// <summary>True when the user chose dbsh as the migration engine.</summary>
    public bool UseDbsh => MigrationEngine == "dbsh";

    /// <summary>dbsh module name derived from <see cref="ModuleNameLower"/> (Module name, lower-case).</summary>
    public string DbshModuleName => ModuleNameLower;

    /// <summary>EF Core DbContextOptions extension method name.</summary>
    public string UseDbMethod => DbProviderInfo.UseMethod(DbProvider);

    /// <summary>EF Core package name for the provider.</summary>
    public string EfProviderPackage => DbProviderInfo.Package(DbProvider);

    /// <summary>EF Core package version for the provider.</summary>
    public string EfProviderVersion => DbProviderInfo.Version(DbProvider);

    /// <summary>Per-module connection string (fallback if not in appsettings).</summary>
    public string ConnectionString =>
        DbProviderInfo.ConnectionString(DbProvider, ModuleName);

    // ── Layer project names (4-layer layout) ──────────────────────
    public string DomainProject => $"{ModuleNamespace}.Domain";
    public string ApplicationProject => $"{ModuleNamespace}.Application";
    public string InfrastructureProject => $"{ModuleNamespace}.Infrastructure";
    public string PresentationProject => $"{ModuleNamespace}.Presentation";

    // Lower-cased module name, used for table prefix + integration event type strings.
    public string ModuleNameLower => ModuleName.ToLowerInvariant();

    // ── Entity being scaffolded (null when generating a blank module) ──
    // Scriban treats "" as truthy, so blank modules must leave these null.
    public string? EntityName { get; set; }       // "Product"
    public string? EntityNameLower { get; set; }  // "product"
    public string? RouteName { get; set; }        // "products"

    /// <summary>Pascal-case plural of <see cref="EntityName"/> (e.g. "Products").</summary>
    public string? EntityPlural => string.IsNullOrEmpty(EntityName)
        ? null
        : CodeGen.Pluralize(EntityName);
}

/// <summary>
/// Model for generating a single command or query handler within an existing module,
/// without creating a full CRUD set.
/// </summary>
internal sealed class FeatureModel
{
    public string RootNamespace { get; set; } = "";
    public string ModuleName { get; set; } = "";        // "Catalog"
    public string ModuleNamespace { get; set; } = "";   // "MyApp.Modules.Catalog"

    // Feature name: "CreateOrder", "PublishEvent", etc.
    public string FeatureName { get; set; } = "";

    // Lowercase first letter: "createOrder", "publishEvent"
    public string FeatureNameLower { get; set; } = "";

    // 4-layer project names
    public string ApplicationProject => $"{ModuleNamespace}.Application";
    public string InfrastructureProject => $"{ModuleNamespace}.Infrastructure";

    public string ModuleNameLower => ModuleName.ToLowerInvariant();
}
