<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Cobytelabs.Modulus.Core" Version="1.2.0" />
    <PackageReference Include="Cobytelabs.Modulus.AspNetCore" Version="1.2.0" />
    <ProjectReference Include="../ProcureFlow.Shared.Application/ProcureFlow.Shared.Application.csproj" />
  </ItemGroup>

</Project>