// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TradeFlow.Modules.Import.Infrastructure.Database;

#nullable disable

namespace TradeFlow.Modules.Import.Infrastructure.Migrations
{
    [DbContext(typeof(ImportDbContext))]
    [Migration("20260901060122_SyncPendingModelChanges")]
    partial class SyncPendingModelChanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("import")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Modulus.Outbox.Abstractions.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CausationId")
                        .HasColumnType("text")
                        .HasColumnName("causation_id");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("text")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("LockedBy")
                        .HasColumnType("text")
                        .HasColumnName("locked_by");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("message_type");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("module_name");

                    b.Property<DateTime?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_outbox_messages_tenant_id");

                    b.HasIndex("ProcessedAt", "CreatedAt")
                        .HasDatabaseName("ix_outbox_messages_processed_at_created_at");

                    b.HasIndex("ProcessedAt", "LockedUntil", "RetryCount")
                        .HasDatabaseName("ix_outbox_messages_processed_at_locked_until_retry_count");

                    b.ToTable("outbox_messages", "import");
                });

            modelBuilder.Entity("TradeFlow.Modules.Import.Domain.Entities.AssessmentVariance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AssessedAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("assessed_amount");

                    b.Property<Guid>("BoeId")
                        .HasColumnType("uuid")
                        .HasColumnName("boe_id");

                    b.Property<Guid>("BoeLineId")
                        .HasColumnType("uuid")
                        .HasColumnName("boe_line_id");

                    b.Property<string>("Component")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("component");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<string>("Resolution")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("resolution");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<decimal>("SystemAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("system_amount");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<decimal>("VarianceAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("variance_amount");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_assessment_variances");

                    b.HasIndex("BoeId")
                        .HasDatabaseName("ix_assessment_variances_boe_id");

                    b.ToTable("assessment_variances", "import");
                });

            modelBuilder.Entity("TradeFlow.Modules.Import.Domain.Entities.BillOfEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("AssessedAt")
                        .HasColumnType("date")
                        .HasColumnName("assessed_at");

                    b.Property<DateOnly>("BoeDate")
                        .HasColumnType("date")
                        .HasColumnName("boe_date");

                    b.Property<string>("BoeNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("boe_number");

                    b.Property<Guid?>("CnfAgentId")
                        .HasColumnType("uuid")
                        .HasColumnName("cnf_agent_id");

                    b.Property<string>("CustomsOffice")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("customs_office");

                    b.Property<string>("DeclarantAin")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("declarant_ain");

                    b.Property<string>("DisputeReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("dispute_reason");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_id");

                    b.Property<int>("Lane")
                        .HasColumnType("integer")
                        .HasColumnName("lane");

                    b.Property<DateOnly?>("PaidAt")
                        .HasColumnType("date")
                        .HasColumnName("paid_at");

                    b.Property<DateOnly?>("ReleasedAt")
                        .HasColumnType("date")
                        .HasColumnName("released_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("TotalAssessableValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("total_assessable_value");

                    b.Property<decimal>("TotalDuty")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("total_duty");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_bills_of_entry");

                    b.HasIndex("FileId")
                        .HasDatabaseName("ix_bills_of_entry_file_id");

                    b.HasIndex("TenantId", "BoeNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_bills_of_entry_tenant_id_boe_number");

                    b.ToTable("bills_of_entry", "import");
                });

            modelBuilder.Entity("TradeFlow.Modules.Import.Domain.Entities.CertificateOfOrigin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CiId")
                        .HasColumnType("uuid")
                        .HasColumnName("ci_id");

                    b.Property<string>("DocumentNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("document_no");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date")
                        .HasColumnName("expiry_date");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_id");

                    b.Property<DateOnly>("IssuedOn")
                        .HasColumnType("date")
                        .HasColumnName("issued_on");

                    b.Property<string>("IssuerName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("issuer_name");

                    b.Property<string>("MismatchReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("mismatch_reason");

                    b.Property<string>("OriginCountry")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("origin_country");

                    b.Property<bool>("PreferentialEligible")
                        .HasColumnType("boolean")
                        .HasColumnName("preferential_eligible");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_certificates_of_origin");

                    b.HasIndex("TenantId", "DocumentNo")
                        .IsUnique()
                        .HasDatabaseName("ix_certificates_of_origin_tenant_id_document_no");

                    b.HasIndex("TenantId", "FileId")
                        .IsUnique()
                        .HasDatabaseName("ix_certificates_of_origin_tenant_id_file_id");

                    b.ToTable("certificates_of_origin", "import");
                });

            modelBuilder.Entity("TradeFlow.Modules.Import.Domain.Entities.CnfAgent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AinNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ain_number");

                    b.Property<string>("Contacts")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("contacts");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<decimal>("RateCardDocumentationCharges")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("rate_card_documentation_charges");

                    b.Property<decimal>("RateCardPctOfValue")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("rate_card_pct_of_value");

                    b.Property<decimal>("RateCardPerBoe")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("rate_card_per_boe");

                    b.Property<decimal>("RateCardPerContainer")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("rate_card_per_container");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_cnf_agents");

                    b.HasIndex("TenantId", "AinNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_cnf_agents_tenant_id_ain_number");

                    b.ToTable("cnf_agents", "import");
                });

            modelBuilder.Entity("TradeFlow.Modules.Import.Domain.Entities.CommercialInvoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CiNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ci_number");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_id");

                    b.Property<DateOnly>("IssuedOn")
                        .HasColumnType("date")
                        .HasColumnName("issued_on");

                    b.Property<Guid?>("PiId")
                        .HasColumnType("uuid")
                        .HasColumnName("pi_id");

                    b.Property<string>("ReceivedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("received_by");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("TotalFcy")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("total_fcy");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_commercial_invoices");

                    b.HasIndex("TenantId", "CiNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_commercial_invoices_tenant_id_ci_number");

                    b.ToTable("commercial_invoices", "import");
                });

            modelBuilder.Entity("TradeFlow.Modules.Import.Domain.Entities.CooIssuerRegistry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("country");

                    b.Property<string>("IssuerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("issuer_name");

                    b.Property<string>("LicenseNo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("license_no");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date")
                        .HasColumnName("valid_from");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date")
                        .HasColumnName("valid_to");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_coo_issuer_registries");

                    b.HasIndex("TenantId", "Country", "IssuerName")
                        .IsUnique()
                        .HasDatabaseName("ix_coo_issuer_registries_tenant_id_country_issuer_name");

                    b.ToTable("coo_issuer_registries", "import");
                });

            modelBuilder.Entity("TradeFlow.Modules.Import.Domain.Entities.FreightCost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount");

                    b.Property<int>("CostType")
                        .HasColumnType("integer")
                        .HasColumnName("cost_type");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_id");

                    b.Property<DateOnly?>("InvoiceDate")
                        .HasColumnType("date")
                        .HasColumnName("invoice_date");

                    b.Property<string>("InvoiceNo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("invoice_no");

                    b.Property<Guid>("ShipmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("shipment_id");

                    b.Property<int>("Stage")
                        .HasColumnType("integer")
                        .HasColumnName("stage");

                    b.Property<string>("SurchargeType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("surcharge_type");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_freight_costs");

                    b.HasIndex("FileId")
                        .HasDatabaseName("ix_freight_costs_file_id");

                    b.HasIndex("ShipmentId")
                        .HasDatabaseName("ix_freight_costs_shipment_id");

                    b.ToTable("freight_costs", "import");
                });

            modelBuilder.Entity("TradeFlow.Modules.Import.Domain.Entities.ImportFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BoeId")
                        .HasColumnType("uuid")
                        .HasColumnName("boe_id");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cancellation_reason");

                    b.Property<Guid?>("CiId")
                        .HasColumnType("uuid")
                        .HasColumnName("ci_id");

                    b.Property<decimal>("ClearingBalance")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("clearing_balance");

                    b.Property<Guid?>("CnfAgentId")
                        .HasColumnType("uuid")
                        .HasColumnName("cnf_agent_id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<int>("DemurrageFreeDays")
                        .HasColumnType("integer")
                        .HasColumnName("demurrage_free_days");

                    b.Property<string>("DisputeReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("dispute_reason");

                    b.Property<decimal>("EstimatedGoodsValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("estimated_goods_value");

                    b.Property<string>("FileNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("file_number");

                    b.Property<int>("FiscalYear")
                        .HasColumnType("integer")
                        .HasColumnName("fiscal_year");

                    b.Property<bool>("HasMissingMandatoryDocuments")
                        .HasColumnType("boolean")
                        .HasColumnName("has_missing_mandatory_documents");

                    b.Property<bool>("HasUnmatchedImpForm")
                        .HasColumnType("boolean")
                        .HasColumnName("has_unmatched_imp_form");

                    b.Property<string>("HoldReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("hold_reason");

                    b.Property<string>("Incoterm")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("incoterm");

                    b.Property<DateOnly?>("LandingDate")
                        .HasColumnType("date")
                        .HasColumnName("landing_date");

                    b.Property<Guid?>("LcId")
                        .HasColumnType("uuid")
                        .HasColumnName("lc_id");

                    b.Property<Guid?>("PiId")
                        .HasColumnType("uuid")
                        .HasColumnName("pi_id");

                    b.Property<Guid?>("PoId")
                        .HasColumnType("uuid")
                        .HasColumnName("po_id");

                    b.Property<string>("PortOfDischarge")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("port_of_discharge");

                    b.Property<string>("PortOfLoading")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("port_of_loading");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<Guid?>("ShipmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("shipment_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid?>("TtId")
                        .HasColumnType("uuid")
                        .HasColumnName("tt_id");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_import_files");

                    b.HasIndex("TenantId", "FileNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_import_files_tenant_id_file_number");

                    b.HasIndex("TenantId", "CompanyId", "FiscalYear", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("ix_import_files_tenant_id_company_id_fiscal_year_sequence");

                    b.ToTable("import_files", "import");
                });

            modelBuilder.Entity("TradeFlow.Modules.Import.Domain.Entities.ImportPermit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<decimal>("CeilingQty")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("ceiling_qty");

                    b.Property<decimal>("CeilingValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("ceiling_value");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateOnly>("ExpiresOn")
                        .HasColumnType("date")
                        .HasColumnName("expires_on");

                    b.Property<string>("IssuedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("issued_by");

                    b.Property<DateOnly>("IssuedOn")
                        .HasColumnType("date")
                        .HasColumnName("issued_on");

                    b.Property<string>("PermitNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("permit_no");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_import_permits");

                    b.HasIndex("TenantId", "PermitNo")
                        .IsUnique()
                        .HasDatabaseName("ix_import_permits_tenant_id_permit_no");

                    b.ToTable("import_permits", "import");
                });

            modelBuilder.Entity("TradeFlow.Modules.Import.Domain.Entities.ImportPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ApprovedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at_utc");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<int>("FiscalYear")
                        .HasColumnType("integer")
                        .HasColumnName("fiscal_year");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date")
                        .HasColumnName("period_end");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date")
                        .HasColumnName("period_start");

                    b.Property<string>("PlanNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("plan_number");

                    b.Property<int>("PlanVersion")
                        .HasColumnType("integer")
                        .HasColumnName("plan_version");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("TotalEstFob")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("total_est_fob");

                    b.Property<decimal>("TotalEstLanded")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("total_est_landed");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_import_plans");

                    b.HasIndex("TenantId", "FiscalYear")
                        .HasDatabaseName("ix_import_plans_tenant_id_fiscal_year");

                    b.HasIndex("TenantId", "PlanNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_import_plans_tenant_id_plan_number");

                    b.ToTable("import_plans", "import");
                });

            modelBuilder.Entity("TradeFlow.Modules.Import.Domain.Entities.InsurancePolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CiId")
                        .HasColumnType("uuid")
                        .HasColumnName("ci_id");

                    b.Property<string>("CoverNoteRef")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cover_note_ref");

                    b.Property<DateOnly>("CoverStart")
                        .HasColumnType("date")
                        .HasColumnName("cover_start");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_id");

                    b.Property<decimal>("InsuredValueFcy")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("insured_value_fcy");

                    b.Property<string>("Insurer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("insurer");

                    b.Property<string>("PolicyNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("policy_no");

                    b.Property<decimal>("PremiumFcy")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("premium_fcy");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_insurance_policies");

                    b.HasIndex("TenantId", "PolicyNo")
                        .IsUnique()
                        .HasDatabaseName("ix_insurance_policies_tenant_id_policy_no");

                    b.ToTable("insurance_policies", "import");
                });

            modelBuilder.Entity("TradeFlow.Modules.Import.Domain.Entities.PackingList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Cartons")
                        .HasColumnType("integer")
                        .HasColumnName("cartons");

                    b.Property<Guid>("CiId")
                        .HasColumnType("uuid")
                        .HasColumnName("ci_id");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_id");

                    b.Property<decimal>("GrossWeightKg")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("gross_weight_kg");

                    b.Property<decimal>("NetWeightKg")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("net_weight_kg");

                    b.Property<string>("PlNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("pl_number");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<decimal>("VolumeCbm")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("volume_cbm");

                    b.HasKey("Id")
                        .HasName("pk_packing_lists");

                    b.ToTable("packing_lists", "import");
                });

            modelBuilder.Entity("TradeFlow.Modules.Import.Domain.Entities.PortCharge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount");

                    b.Property<int>("ChargeType")
                        .HasColumnType("integer")
                        .HasColumnName("charge_type");

                    b.Property<DateOnly>("ChargedOn")
                        .HasColumnType("date")
                        .HasColumnName("charged_on");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_id");

                    b.Property<string>("ReceiptRef")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("receipt_ref");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_port_charges");

                    b.HasIndex("FileId")
                        .HasDatabaseName("ix_port_charges_file_id");

                    b.ToTable("port_charges", "import");
                });

            modelBuilder.Entity("TradeFlow.Modules.Import.Domain.Entities.ProformaInvoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AcceptedForLc")
                        .HasColumnType("boolean")
                        .HasColumnName("accepted_for_lc");

                    b.Property<string>("BeneficiaryAccount")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("beneficiary_account");

                    b.Property<string>("BeneficiaryBank")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("beneficiary_bank");

                    b.Property<string>("BeneficiaryName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("beneficiary_name");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_id");

                    b.Property<DateOnly>("IssuedOn")
                        .HasColumnType("date")
                        .HasColumnName("issued_on");

                    b.Property<string>("PiNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("pi_number");

                    b.Property<Guid>("PoId")
                        .HasColumnType("uuid")
                        .HasColumnName("po_id");

                    b.Property<string>("ReceivedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("received_by");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateOnly>("ValidUntil")
                        .HasColumnType("date")
                        .HasColumnName("valid_until");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_proforma_invoices");

                    b.HasIndex("TenantId", "PiNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_proforma_invoices_tenant_id_pi_number");

                    b.ToTable("proforma_invoices", "import");
                });

            modelBuilder.Entity("TradeFlow.Modules.Import.Domain.Entities.Shipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("ActualEta")
                        .HasColumnType("date")
                        .HasColumnName("actual_eta");

                    b.Property<Guid?>("CiId")
                        .HasColumnType("uuid")
                        .HasColumnName("ci_id");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateOnly>("Eta")
                        .HasColumnType("date")
                        .HasColumnName("eta");

                    b.Property<DateOnly>("Etd")
                        .HasColumnType("date")
                        .HasColumnName("etd");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_id");

                    b.Property<bool>("LcBreachRiskAlerted")
                        .HasColumnType("boolean")
                        .HasColumnName("lc_breach_risk_alerted");

                    b.Property<int>("Mode")
                        .HasColumnType("integer")
                        .HasColumnName("mode");

                    b.Property<string>("ShipmentNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("shipment_no");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<string>("VesselVoyage")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("vessel_voyage");

                    b.HasKey("Id")
                        .HasName("pk_shipments");

                    b.HasIndex("TenantId", "ShipmentNo")
                        .IsUnique()
                        .HasDatabaseName("ix_shipments_tenant_id_shipment_no");

                    b.ToTable("shipments", "import");
                });

            modelBuilder.Entity("TradeFlow.Modules.Import.Domain.Entities.TransportDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Consignee")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("consignee");

                    b.Property<int>("CustodyHolder")
                        .HasColumnType("integer")
                        .HasColumnName("custody_holder");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("document_number");

                    b.Property<DateOnly?>("EndorsedAt")
                        .HasColumnType("date")
                        .HasColumnName("endorsed_at");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_id");

                    b.Property<string>("FreightTerms")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("freight_terms");

                    b.Property<DateOnly>("IssueDate")
                        .HasColumnType("date")
                        .HasColumnName("issue_date");

                    b.Property<string>("NotifyParty")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notify_party");

                    b.Property<DateOnly?>("OnBoardDate")
                        .HasColumnType("date")
                        .HasColumnName("on_board_date");

                    b.Property<int>("OriginalCount")
                        .HasColumnType("integer")
                        .HasColumnName("original_count");

                    b.Property<Guid>("ShipmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("shipment_id");

                    b.Property<int>("SurrenderStatus")
                        .HasColumnType("integer")
                        .HasColumnName("surrender_status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_transport_documents");

                    b.HasIndex("FileId")
                        .HasDatabaseName("ix_transport_documents_file_id");

                    b.HasIndex("ShipmentId")
                        .HasDatabaseName("ix_transport_documents_shipment_id");

                    b.HasIndex("TenantId", "DocumentNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_transport_documents_tenant_id_document_number");

                    b.ToTable("transport_documents", "import");
                });

            modelBuilder.Entity("TradeFlow.Modules.Import.Domain.Entities.BillOfEntry", b =>
                {
                    b.OwnsMany("TradeFlow.Modules.Import.Domain.Entities.BoeDutyLine", "DutyLines", b1 =>
                        {
                            b1.Property<Guid>("BoeId")
                                .HasColumnType("uuid")
                                .HasColumnName("boe_id");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("amount");

                            b1.Property<string>("Component")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("component");

                            b1.Property<decimal>("Rate")
                                .HasPrecision(9, 6)
                                .HasColumnType("numeric(9,6)")
                                .HasColumnName("rate");

                            b1.Property<string>("SroRef")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("sro_ref");

                            b1.HasKey("BoeId", "Id")
                                .HasName("pk_boe_duty_lines");

                            b1.ToTable("boe_duty_lines", "import");

                            b1.WithOwner()
                                .HasForeignKey("BoeId")
                                .HasConstraintName("fk_boe_duty_lines_bills_of_entry_boe_id");
                        });

                    b.OwnsMany("TradeFlow.Modules.Import.Domain.Entities.BoeLine", "Lines", b1 =>
                        {
                            b1.Property<Guid>("BoeId")
                                .HasColumnType("uuid")
                                .HasColumnName("boe_id");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("AssessableValue")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("assessable_value");

                            b1.Property<Guid?>("CiLineId")
                                .HasColumnType("uuid")
                                .HasColumnName("ci_line_id");

                            b1.Property<string>("HsCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("hs_code");

                            b1.Property<decimal>("Quantity")
                                .HasColumnType("numeric")
                                .HasColumnName("quantity");

                            b1.Property<string>("Uom")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("uom");

                            b1.HasKey("BoeId", "Id")
                                .HasName("pk_boe_lines");

                            b1.ToTable("boe_lines", "import");

                            b1.WithOwner()
                                .HasForeignKey("BoeId")
                                .HasConstraintName("fk_boe_lines_bills_of_entry_boe_id");
                        });

                    b.OwnsMany("TradeFlow.Modules.Import.Domain.Entities.BoeMilestone", "Milestones", b1 =>
                        {
                            b1.Property<Guid>("BoeId")
                                .HasColumnType("uuid")
                                .HasColumnName("boe_id");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("AtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("at_utc");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("name");

                            b1.HasKey("BoeId", "Id")
                                .HasName("pk_boe_milestones");

                            b1.ToTable("boe_milestones", "import");

                            b1.WithOwner()
                                .HasForeignKey("BoeId")
                                .HasConstraintName("fk_boe_milestones_bills_of_entry_boe_id");
                        });

                    b.Navigation("DutyLines");

                    b.Navigation("Lines");

                    b.Navigation("Milestones");
                });

            modelBuilder.Entity("TradeFlow.Modules.Import.Domain.Entities.CnfAgent", b =>
                {
                    b.OwnsMany("TradeFlow.Modules.Import.Domain.Entities.CnfChargeBill", "ChargeBills", b1 =>
                        {
                            b1.Property<Guid>("AgentId")
                                .HasColumnType("uuid")
                                .HasColumnName("agent_id");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("AmountBdt")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("amount_bdt");

                            b1.Property<string>("BillNo")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("bill_no");

                            b1.Property<Guid>("FileId")
                                .HasColumnType("uuid")
                                .HasColumnName("file_id");

                            b1.Property<bool>("Verified")
                                .HasColumnType("boolean")
                                .HasColumnName("verified");

                            b1.HasKey("AgentId", "Id")
                                .HasName("pk_cnf_charge_bills");

                            b1.ToTable("cnf_charge_bills", "import");

                            b1.WithOwner()
                                .HasForeignKey("AgentId")
                                .HasConstraintName("fk_cnf_charge_bills_cnf_agents_agent_id");
                        });

                    b.Navigation("ChargeBills");
                });

            modelBuilder.Entity("TradeFlow.Modules.Import.Domain.Entities.CommercialInvoice", b =>
                {
                    b.OwnsMany("TradeFlow.Modules.Import.Domain.Entities.CommercialInvoiceLine", "Lines", b1 =>
                        {
                            b1.Property<Guid>("CiId")
                                .HasColumnType("uuid")
                                .HasColumnName("ci_id");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid?>("BoeLineId")
                                .HasColumnType("uuid")
                                .HasColumnName("boe_line_id");

                            b1.Property<decimal?>("BoeQuantity")
                                .HasColumnType("numeric")
                                .HasColumnName("boe_quantity");

                            b1.Property<decimal?>("BoeValue")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("boe_value");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("description");

                            b1.Property<Guid?>("PiLineId")
                                .HasColumnType("uuid")
                                .HasColumnName("pi_line_id");

                            b1.Property<decimal>("Quantity")
                                .HasColumnType("numeric")
                                .HasColumnName("quantity");

                            b1.Property<decimal>("UnitPrice")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("unit_price");

                            b1.Property<string>("Uom")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("uom");

                            b1.HasKey("CiId", "Id")
                                .HasName("pk_ci_lines");

                            b1.ToTable("ci_lines", "import");

                            b1.WithOwner()
                                .HasForeignKey("CiId")
                                .HasConstraintName("fk_ci_lines_commercial_invoices_ci_id");
                        });

                    b.Navigation("Lines");
                });

            modelBuilder.Entity("TradeFlow.Modules.Import.Domain.Entities.ImportFile", b =>
                {
                    b.OwnsMany("TradeFlow.Modules.Import.Domain.Entities.FileDocument", "Documents", b1 =>
                        {
                            b1.Property<Guid>("FileId")
                                .HasColumnType("uuid")
                                .HasColumnName("file_id");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<bool>("IsMandatory")
                                .HasColumnType("boolean")
                                .HasColumnName("is_mandatory");

                            b1.Property<bool>("IsPresent")
                                .HasColumnType("boolean")
                                .HasColumnName("is_present");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("name");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("type");

                            b1.HasKey("FileId", "Id")
                                .HasName("pk_import_file_documents");

                            b1.ToTable("import_file_documents", "import");

                            b1.WithOwner()
                                .HasForeignKey("FileId")
                                .HasConstraintName("fk_import_file_documents_import_files_file_id");
                        });

                    b.OwnsMany("TradeFlow.Modules.Import.Domain.Entities.ImportContainer", "Containers", b1 =>
                        {
                            b1.Property<Guid>("FileId")
                                .HasColumnType("uuid")
                                .HasColumnName("file_id");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("ContainerNo")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("character varying(11)")
                                .HasColumnName("container_no");

                            b1.Property<bool>("DemurrageAlerted70")
                                .HasColumnType("boolean")
                                .HasColumnName("demurrage_alerted70");

                            b1.Property<DateOnly?>("FreeDaysEnd")
                                .HasColumnType("date")
                                .HasColumnName("free_days_end");

                            b1.Property<DateTime?>("GateInAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("gate_in_at_utc");

                            b1.Property<DateTime?>("GateOutAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("gate_out_at_utc");

                            b1.Property<string>("IsoCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("iso_code");

                            b1.Property<string>("SealNo")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("seal_no");

                            b1.Property<string>("SizeType")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("size_type");

                            b1.HasKey("FileId", "Id")
                                .HasName("pk_import_containers");

                            b1.ToTable("import_containers", "import");

                            b1.WithOwner()
                                .HasForeignKey("FileId")
                                .HasConstraintName("fk_import_containers_import_files_file_id");

                            b1.OwnsMany("TradeFlow.Modules.Import.Domain.Entities.ContainerEvent", "Events", b2 =>
                                {
                                    b2.Property<Guid>("FileId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("file_id");

                                    b2.Property<Guid>("ContainerId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("container_id");

                                    b2.Property<Guid>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<DateTime>("AtUtc")
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("at_utc");

                                    b2.Property<string>("Type")
                                        .IsRequired()
                                        .HasMaxLength(20)
                                        .HasColumnType("character varying(20)")
                                        .HasColumnName("type");

                                    b2.HasKey("FileId", "ContainerId", "Id")
                                        .HasName("pk_import_container_events");

                                    b2.ToTable("import_container_events", "import");

                                    b2.WithOwner()
                                        .HasForeignKey("FileId", "ContainerId")
                                        .HasConstraintName("fk_import_container_events_import_containers_file_id_container");
                                });

                            b1.Navigation("Events");
                        });

                    b.OwnsMany("TradeFlow.Modules.Import.Domain.Entities.ImportCostEntry", "CostEntries", b1 =>
                        {
                            b1.Property<Guid>("FileId")
                                .HasColumnType("uuid")
                                .HasColumnName("file_id");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("AmountBdt")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("amount_bdt");

                            b1.Property<decimal>("AmountFcy")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("amount_fcy");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("currency");

                            b1.Property<int>("Direction")
                                .HasColumnType("integer")
                                .HasColumnName("direction");

                            b1.Property<string>("Element")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("element");

                            b1.Property<Guid>("SourceDocId")
                                .HasColumnType("uuid")
                                .HasColumnName("source_doc_id");

                            b1.Property<string>("SourceDocNumber")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("source_doc_number");

                            b1.Property<string>("SourceDocType")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("source_doc_type");

                            b1.HasKey("FileId", "Id")
                                .HasName("pk_import_cost_entries");

                            b1.ToTable("import_cost_entries", "import");

                            b1.WithOwner()
                                .HasForeignKey("FileId")
                                .HasConstraintName("fk_import_cost_entries_import_files_file_id");
                        });

                    b.OwnsMany("TradeFlow.Modules.Import.Domain.Entities.ImportMilestone", "Milestones", b1 =>
                        {
                            b1.Property<Guid>("FileId")
                                .HasColumnType("uuid")
                                .HasColumnName("file_id");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("name");

                            b1.Property<string>("Note")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("note");

                            b1.Property<DateTime>("OccurredAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("occurred_at_utc");

                            b1.HasKey("FileId", "Id")
                                .HasName("pk_import_milestones");

                            b1.ToTable("import_milestones", "import");

                            b1.WithOwner()
                                .HasForeignKey("FileId")
                                .HasConstraintName("fk_import_milestones_import_files_file_id");
                        });

                    b.Navigation("Containers");

                    b.Navigation("CostEntries");

                    b.Navigation("Documents");

                    b.Navigation("Milestones");
                });

            modelBuilder.Entity("TradeFlow.Modules.Import.Domain.Entities.ImportPermit", b =>
                {
                    b.OwnsMany("TradeFlow.Modules.Import.Domain.Entities.PermitUtilization", "Utilizations", b1 =>
                        {
                            b1.Property<Guid>("PermitId")
                                .HasColumnType("uuid")
                                .HasColumnName("permit_id");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateOnly>("DrawnOn")
                                .HasColumnType("date")
                                .HasColumnName("drawn_on");

                            b1.Property<Guid>("FileId")
                                .HasColumnType("uuid")
                                .HasColumnName("file_id");

                            b1.Property<decimal>("Quantity")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("quantity");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("value");

                            b1.HasKey("PermitId", "Id")
                                .HasName("pk_permit_utilizations");

                            b1.ToTable("permit_utilizations", "import");

                            b1.WithOwner()
                                .HasForeignKey("PermitId")
                                .HasConstraintName("fk_permit_utilizations_import_permits_permit_id");
                        });

                    b.Navigation("Utilizations");
                });

            modelBuilder.Entity("TradeFlow.Modules.Import.Domain.Entities.ImportPlan", b =>
                {
                    b.OwnsMany("TradeFlow.Modules.Import.Domain.Entities.ImportPlanLine", "Lines", b1 =>
                        {
                            b1.Property<Guid>("PlanId")
                                .HasColumnType("uuid")
                                .HasColumnName("plan_id");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("ActualFob")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("actual_fob");

                            b1.Property<decimal>("ActualLanded")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("actual_landed");

                            b1.Property<decimal>("ActualQty")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("actual_qty");

                            b1.Property<Guid?>("CategoryId")
                                .HasColumnType("uuid")
                                .HasColumnName("category_id");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("description");

                            b1.Property<decimal>("EstFob")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("est_fob");

                            b1.Property<decimal>("EstLanded")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("est_landed");

                            b1.Property<decimal>("EstQty")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("est_qty");

                            b1.Property<Guid?>("ItemId")
                                .HasColumnType("uuid")
                                .HasColumnName("item_id");

                            b1.Property<string>("SourceCountry")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("source_country");

                            b1.Property<decimal?>("TargetMonth")
                                .HasColumnType("numeric")
                                .HasColumnName("target_month");

                            b1.HasKey("PlanId", "Id")
                                .HasName("pk_import_plan_lines");

                            b1.ToTable("import_plan_lines", "import");

                            b1.WithOwner()
                                .HasForeignKey("PlanId")
                                .HasConstraintName("fk_import_plan_lines_import_plans_plan_id");
                        });

                    b.Navigation("Lines");
                });

            modelBuilder.Entity("TradeFlow.Modules.Import.Domain.Entities.PackingList", b =>
                {
                    b.OwnsMany("TradeFlow.Modules.Import.Domain.Entities.PackingListLine", "Lines", b1 =>
                        {
                            b1.Property<Guid>("PlId")
                                .HasColumnType("uuid")
                                .HasColumnName("pl_id");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("CiLineId")
                                .HasColumnType("uuid")
                                .HasColumnName("ci_line_id");

                            b1.Property<decimal>("GrossWeightKg")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("gross_weight_kg");

                            b1.Property<decimal>("NetWeightKg")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("net_weight_kg");

                            b1.Property<decimal>("Quantity")
                                .HasColumnType("numeric")
                                .HasColumnName("quantity");

                            b1.Property<string>("Uom")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("uom");

                            b1.Property<decimal>("VolumeCbm")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("volume_cbm");

                            b1.HasKey("PlId", "Id")
                                .HasName("pk_pl_lines");

                            b1.ToTable("pl_lines", "import");

                            b1.WithOwner()
                                .HasForeignKey("PlId")
                                .HasConstraintName("fk_pl_lines_packing_lists_pl_id");
                        });

                    b.Navigation("Lines");
                });

            modelBuilder.Entity("TradeFlow.Modules.Import.Domain.Entities.ProformaInvoice", b =>
                {
                    b.OwnsMany("TradeFlow.Modules.Import.Domain.Entities.ProformaInvoiceLine", "Lines", b1 =>
                        {
                            b1.Property<Guid>("PiId")
                                .HasColumnType("uuid")
                                .HasColumnName("pi_id");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("description");

                            b1.Property<Guid?>("ItemId")
                                .HasColumnType("uuid")
                                .HasColumnName("item_id");

                            b1.Property<Guid?>("PoLineId")
                                .HasColumnType("uuid")
                                .HasColumnName("po_line_id");

                            b1.Property<decimal>("Quantity")
                                .HasColumnType("numeric")
                                .HasColumnName("quantity");

                            b1.Property<decimal>("UnitPrice")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("unit_price");

                            b1.Property<string>("Uom")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("uom");

                            b1.Property<string>("VarianceNote")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("variance_note");

                            b1.HasKey("PiId", "Id")
                                .HasName("pk_pi_lines");

                            b1.ToTable("pi_lines", "import");

                            b1.WithOwner()
                                .HasForeignKey("PiId")
                                .HasConstraintName("fk_pi_lines_proforma_invoices_pi_id");
                        });

                    b.Navigation("Lines");
                });

            modelBuilder.Entity("TradeFlow.Modules.Import.Domain.Entities.Shipment", b =>
                {
                    b.OwnsMany("TradeFlow.Modules.Import.Domain.Entities.ShipmentMilestone", "Milestones", b1 =>
                        {
                            b1.Property<Guid>("ShipmentId")
                                .HasColumnType("uuid")
                                .HasColumnName("shipment_id");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("AtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("at_utc");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("name");

                            b1.Property<string>("Note")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("note");

                            b1.HasKey("ShipmentId", "Id")
                                .HasName("pk_shipment_milestones");

                            b1.ToTable("shipment_milestones", "import");

                            b1.WithOwner()
                                .HasForeignKey("ShipmentId")
                                .HasConstraintName("fk_shipment_milestones_shipments_shipment_id");
                        });

                    b.Navigation("Milestones");
                });
#pragma warning restore 612, 618
        }
    }
}
