<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Description>Amazon S3 file storage provider for Modulus.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Modulus.Platform/Modulus.Platform.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.S3" />
  </ItemGroup>

</Project>
