<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Modulus.Inbox/Modulus.Inbox.csproj" />
    <ProjectReference Include="../Modulus.Inbox/Modulus.Inbox.csproj" />
    <ProjectReference Include="../../data/Modulus.Data.MongoDB/Modulus.Data.MongoDB.csproj" />
  </ItemGroup>

</Project>
