<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Modulus.Data.Abstractions/Modulus.Data.Abstractions.csproj" />
    <PackageReference Include="MongoDB.Driver" />
  </ItemGroup>

</Project>
