// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TradeFlow.Modules.Finance.Infrastructure.Database;

#nullable disable

namespace TradeFlow.Modules.Finance.Infrastructure.Migrations
{
    [DbContext(typeof(FinanceDbContext))]
    [Migration("20260901060115_SyncPendingModelChanges")]
    partial class SyncPendingModelChanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("finance")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Modulus.Outbox.Abstractions.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CausationId")
                        .HasColumnType("text")
                        .HasColumnName("causation_id");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("text")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("LockedBy")
                        .HasColumnType("text")
                        .HasColumnName("locked_by");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("message_type");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("module_name");

                    b.Property<DateTime?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_financeoutbox_messages");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_financeoutbox_messages_tenant_id");

                    b.HasIndex("ProcessedAt", "CreatedAt")
                        .HasDatabaseName("ix_financeoutbox_messages_processed_at_created_at");

                    b.HasIndex("ProcessedAt", "LockedUntil", "RetryCount")
                        .HasDatabaseName("ix_financeoutbox_messages_processed_at_locked_until_retry_count");

                    b.ToTable("Financeoutbox_messages", "finance");
                });

            modelBuilder.Entity("TradeFlow.Modules.Finance.Domain.Entities.ApInvoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ApprovedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at_utc");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("text")
                        .HasColumnName("approved_by");

                    b.Property<string>("CancelReason")
                        .HasColumnType("text")
                        .HasColumnName("cancel_reason");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<DateOnly>("InvoiceDate")
                        .HasColumnType("date")
                        .HasColumnName("invoice_date");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("invoice_number");

                    b.Property<bool>("IsCreditNote")
                        .HasColumnType("boolean")
                        .HasColumnName("is_credit_note");

                    b.Property<DateOnly?>("ReceivedDate")
                        .HasColumnType("date")
                        .HasColumnName("received_date");

                    b.Property<int>("Source")
                        .HasColumnType("integer")
                        .HasColumnName("source");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("total_amount");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid")
                        .HasColumnName("vendor_id");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_financeap_invoices");

                    b.HasIndex("DueDate")
                        .HasDatabaseName("ix_financeap_invoices_due_date");

                    b.HasIndex("InvoiceNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_financeap_invoices_invoice_number");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_financeap_invoices_status");

                    b.HasIndex("VendorId")
                        .HasDatabaseName("ix_financeap_invoices_vendor_id");

                    b.ToTable("Financeap_invoices", "finance");
                });

            modelBuilder.Entity("TradeFlow.Modules.Finance.Domain.Entities.ApPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount");

                    b.Property<Guid?>("ApInvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("ap_invoice_id");

                    b.Property<string>("BankReference")
                        .HasColumnType("text")
                        .HasColumnName("bank_reference");

                    b.Property<DateTime?>("ClearedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cleared_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<DateOnly>("PaymentDate")
                        .HasColumnType("date")
                        .HasColumnName("payment_date");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reference_number");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_financeap_payments");

                    b.HasIndex("ApInvoiceId")
                        .HasDatabaseName("ix_financeap_payments_ap_invoice_id");

                    b.HasIndex("InvoiceId")
                        .HasDatabaseName("ix_financeap_payments_invoice_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_financeap_payments_status");

                    b.ToTable("Financeap_payments", "finance");
                });

            modelBuilder.Entity("TradeFlow.Modules.Finance.Domain.Entities.CostCenter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_financecost_centers");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_financecost_centers_code");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_financecost_centers_parent_id");

                    b.ToTable("Financecost_centers", "finance");
                });

            modelBuilder.Entity("TradeFlow.Modules.Finance.Domain.Entities.FxRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date")
                        .HasColumnName("effective_date");

                    b.Property<string>("FromCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("from_currency");

                    b.Property<decimal>("Rate")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("rate");

                    b.Property<int>("Source")
                        .HasColumnType("integer")
                        .HasColumnName("source");

                    b.Property<string>("SourceReference")
                        .HasColumnType("text")
                        .HasColumnName("source_reference");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("ToCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("to_currency");

                    b.Property<DateTime>("UploadedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_financefx_rates");

                    b.HasIndex("FromCurrency")
                        .HasDatabaseName("ix_financefx_rates_from_currency");

                    b.HasIndex("ToCurrency")
                        .HasDatabaseName("ix_financefx_rates_to_currency");

                    b.HasIndex("EffectiveDate", "FromCurrency", "ToCurrency")
                        .IsUnique()
                        .HasDatabaseName("ix_financefx_rates_effective_date_from_currency_to_currency");

                    b.ToTable("Financefx_rates", "finance");
                });

            modelBuilder.Entity("TradeFlow.Modules.Finance.Domain.Entities.GrIrAccrual", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount");

                    b.Property<string>("ClearedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cleared_by");

                    b.Property<DateOnly?>("ClearedOn")
                        .HasColumnType("date")
                        .HasColumnName("cleared_on");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<Guid>("GrnId")
                        .HasColumnType("uuid")
                        .HasColumnName("grn_id");

                    b.Property<string>("GrnNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("grn_number");

                    b.Property<Guid?>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<Guid?>("PoId")
                        .HasColumnType("uuid")
                        .HasColumnName("po_id");

                    b.Property<DateOnly>("ReceivedOn")
                        .HasColumnType("date")
                        .HasColumnName("received_on");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid")
                        .HasColumnName("vendor_id");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_financegr_ir_accruals");

                    b.HasIndex("GrnId")
                        .IsUnique()
                        .HasDatabaseName("ix_financegr_ir_accruals_grn_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_financegr_ir_accruals_status");

                    b.HasIndex("VendorId")
                        .HasDatabaseName("ix_financegr_ir_accruals_vendor_id");

                    b.ToTable("Financegr_ir_accruals", "finance");
                });

            modelBuilder.Entity("TradeFlow.Modules.Finance.Domain.Entities.InvoiceLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ApInvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("ap_invoice_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<Guid?>("GrnLineId")
                        .HasColumnType("uuid")
                        .HasColumnName("grn_line_id");

                    b.Property<decimal>("LineTotal")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("line_total");

                    b.Property<string>("MatchReason")
                        .HasColumnType("text")
                        .HasColumnName("match_reason");

                    b.Property<int>("MatchStatus")
                        .HasColumnType("integer")
                        .HasColumnName("match_status");

                    b.Property<Guid>("PoLineId")
                        .HasColumnType("uuid")
                        .HasColumnName("po_line_id");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("unit_price");

                    b.Property<string>("Uom")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("uom");

                    b.HasKey("Id")
                        .HasName("pk_financeinvoice_lines");

                    b.HasIndex("ApInvoiceId")
                        .HasDatabaseName("ix_financeinvoice_lines_ap_invoice_id");

                    b.ToTable("Financeinvoice_lines", "finance");
                });

            modelBuilder.Entity("TradeFlow.Modules.Finance.Domain.Entities.JournalBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("JournalNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("journal_number");

                    b.Property<DateTime?>("PostedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("posted_at_utc");

                    b.Property<string>("PostedBy")
                        .HasColumnType("text")
                        .HasColumnName("posted_by");

                    b.Property<DateOnly>("PostingDate")
                        .HasColumnType("date")
                        .HasColumnName("posting_date");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_financejournal_batches");

                    b.HasIndex("JournalNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_financejournal_batches_journal_number");

                    b.HasIndex("PostingDate")
                        .HasDatabaseName("ix_financejournal_batches_posting_date");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_financejournal_batches_status");

                    b.ToTable("Financejournal_batches", "finance");
                });

            modelBuilder.Entity("TradeFlow.Modules.Finance.Domain.Entities.JournalLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("account_code");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("account_name");

                    b.Property<Guid?>("CostCenterId")
                        .HasColumnType("uuid")
                        .HasColumnName("cost_center_id");

                    b.Property<decimal>("Credit")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("credit");

                    b.Property<decimal>("Debit")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("debit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<Guid?>("JournalBatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("journal_batch_id");

                    b.HasKey("Id")
                        .HasName("pk_financejournal_lines");

                    b.HasIndex("JournalBatchId")
                        .HasDatabaseName("ix_financejournal_lines_journal_batch_id");

                    b.ToTable("Financejournal_lines", "finance");
                });

            modelBuilder.Entity("TradeFlow.Modules.Finance.Domain.Entities.MatchException", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<Guid>("InvoiceLineId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_line_id");

                    b.Property<decimal>("InvoicePrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("invoice_price");

                    b.Property<decimal>("InvoiceQty")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("invoice_qty");

                    b.Property<decimal>("MatchedPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("matched_price");

                    b.Property<decimal>("MatchedQty")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("matched_qty");

                    b.Property<string>("Resolution")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("resolution");

                    b.Property<DateTime?>("ResolvedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at_utc");

                    b.Property<string>("ResolvedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("resolved_by");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_financematch_exceptions");

                    b.HasIndex("InvoiceId")
                        .HasDatabaseName("ix_financematch_exceptions_invoice_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_financematch_exceptions_status");

                    b.ToTable("Financematch_exceptions", "finance");
                });

            modelBuilder.Entity("TradeFlow.Modules.Finance.Domain.Entities.PaymentProposal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ApprovedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at_utc");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("text")
                        .HasColumnName("approved_by");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<DateOnly>("PaymentDate")
                        .HasColumnType("date")
                        .HasColumnName("payment_date");

                    b.Property<string>("ProposalNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("proposal_number");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("total_amount");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<string>("_invoiceIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("InvoiceIds");

                    b.HasKey("Id")
                        .HasName("pk_financepayment_proposals");

                    b.HasIndex("ProposalNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_financepayment_proposals_proposal_number");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_financepayment_proposals_status");

                    b.ToTable("Financepayment_proposals", "finance");
                });

            modelBuilder.Entity("TradeFlow.Modules.Finance.Domain.Entities.ApPayment", b =>
                {
                    b.HasOne("TradeFlow.Modules.Finance.Domain.Entities.ApInvoice", null)
                        .WithMany("Payments")
                        .HasForeignKey("ApInvoiceId")
                        .HasConstraintName("fk_financeap_payments_financeap_invoices_ap_invoice_id");
                });

            modelBuilder.Entity("TradeFlow.Modules.Finance.Domain.Entities.InvoiceLine", b =>
                {
                    b.HasOne("TradeFlow.Modules.Finance.Domain.Entities.ApInvoice", null)
                        .WithMany("Lines")
                        .HasForeignKey("ApInvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_financeinvoice_lines_financeap_invoices_ap_invoice_id");
                });

            modelBuilder.Entity("TradeFlow.Modules.Finance.Domain.Entities.JournalLine", b =>
                {
                    b.HasOne("TradeFlow.Modules.Finance.Domain.Entities.JournalBatch", null)
                        .WithMany("Lines")
                        .HasForeignKey("JournalBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_financejournal_lines_financejournal_batches_journal_batch_id");
                });

            modelBuilder.Entity("TradeFlow.Modules.Finance.Domain.Entities.ApInvoice", b =>
                {
                    b.Navigation("Lines");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("TradeFlow.Modules.Finance.Domain.Entities.JournalBatch", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
