// <auto-generated />
using System;
using ModulusSample.Modules.Identity.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ModulusSample.Modules.Identity.Infrastructure.Database.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    [Migration("20260518063130_RefactorUsersToOwnsManyPattern")]
    partial class RefactorUsersToOwnsManyPattern
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("identity")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ModulusSample.Modules.Identity.Domain.Entities.DataExportRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<string>("DownloadUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("download_url");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("error_message");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<DateTime>("RequestedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at_utc")
                        .HasDefaultValueSql("(NOW() AT TIME ZONE 'UTC')");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_data_export_requests");

                    b.HasIndex("CompletedAtUtc")
                        .HasDatabaseName("ix_data_export_requests_completed_at_utc");

                    b.HasIndex("ExpiresAtUtc")
                        .HasDatabaseName("ix_data_export_requests_expires_at_utc");

                    b.HasIndex("RequestedAtUtc")
                        .HasDatabaseName("ix_data_export_requests_requested_at_utc");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_data_export_requests_status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_data_export_requests_user_id");

                    b.HasIndex("Status", "ExpiresAtUtc")
                        .HasDatabaseName("ix_data_export_requests_status_expires_at_utc");

                    b.HasIndex("Status", "RequestedAtUtc")
                        .HasDatabaseName("ix_data_export_requests_status_requested_at_utc");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("ix_data_export_requests_user_id_status");

                    b.ToTable("data_export_requests", "identity");
                });

            modelBuilder.Entity("ModulusSample.Modules.Identity.Domain.Entities.DeviceToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(NOW() AT TIME ZONE 'UTC')");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("device_type");

                    b.Property<DateTime?>("ExpiresAt")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("token");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_device_tokens");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_device_tokens_expires_at");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_device_tokens_is_active");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_device_tokens_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_device_tokens_user_id");

                    b.HasIndex("UserId", "DeviceType")
                        .HasDatabaseName("ix_device_tokens_user_id_device_type");

                    b.ToTable("device_tokens", "identity");
                });

            modelBuilder.Entity("ModulusSample.Modules.Identity.Domain.Entities.EmailVerificationToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_used");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<DateTime?>("UsedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_email_verification_tokens");

                    b.HasIndex("ExpiresAtUtc")
                        .HasDatabaseName("ix_email_verification_tokens_expires");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_email_verification_tokens_hash");

                    b.HasIndex("UserId", "IsUsed", "CreatedAtUtc")
                        .HasDatabaseName("ix_email_verification_tokens_user_created");

                    b.ToTable("email_verification_tokens", "identity");
                });

            modelBuilder.Entity("ModulusSample.Modules.Identity.Domain.Entities.ExternalLogin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("LastUsedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at_utc")
                        .HasDefaultValueSql("(NOW() AT TIME ZONE 'UTC')");

                    b.Property<DateTime>("LinkedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("linked_at_utc")
                        .HasDefaultValueSql("(NOW() AT TIME ZONE 'UTC')");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("provider_email");

                    b.Property<string>("ProviderUserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("provider_user_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_external_logins");

                    b.HasIndex("LinkedAtUtc")
                        .HasDatabaseName("ix_external_logins_linked_at_utc");

                    b.HasIndex("Provider")
                        .HasDatabaseName("ix_external_logins_provider");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_external_logins_user_id");

                    b.HasIndex("Provider", "ProviderUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_external_logins_provider_provider_user_id");

                    b.ToTable("external_logins", "identity");
                });

            modelBuilder.Entity("ModulusSample.Modules.Identity.Domain.Entities.Permission", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("(NOW() AT TIME ZONE 'UTC')");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_permissions");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_permissions_category");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_permissions_code");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_permissions_is_active");

                    b.HasIndex("Category", "IsActive")
                        .HasDatabaseName("ix_permissions_category_is_active");

                    b.ToTable("permissions", "identity");
                });

            modelBuilder.Entity("ModulusSample.Modules.Identity.Domain.Entities.PhoneVerification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempt_count");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(NOW() AT TIME ZONE 'UTC')");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_verified");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.HasKey("Id")
                        .HasName("pk_phone_verifications");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_phone_verifications_expires_at");

                    b.HasIndex("IsVerified")
                        .HasDatabaseName("ix_phone_verifications_is_verified");

                    b.HasIndex("PhoneNumber")
                        .HasDatabaseName("ix_phone_verifications_phone_number");

                    b.ToTable("phone_verifications", "identity");
                });

            modelBuilder.Entity("ModulusSample.Modules.Identity.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsSystem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("IsSystem")
                        .HasDatabaseName("ix_roles_is_system");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_name");

                    b.ToTable("roles", "identity");
                });

            modelBuilder.Entity("ModulusSample.Modules.Identity.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AccountDeletionRequestedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("account_deletion_requested_at_utc");

                    b.Property<DateTime?>("AccountDeletionScheduledFor")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("account_deletion_scheduled_for");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<int>("CurrentSubAccountsCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("current_sub_accounts_count");

                    b.Property<DateTime?>("DataExportRequestedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_export_requested_at_utc");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("DeletionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("deletion_reason");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("email_confirmed");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("GdprConsentGiven")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("gdpr_consent_given");

                    b.Property<DateTime?>("GdprConsentGivenAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("gdpr_consent_given_at_utc");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastActivityAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_activity_at_utc");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at_utc");

                    b.Property<DateTime?>("LastModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at_utc");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<DateTime?>("LastSyncedWithKeycloakAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_with_keycloak_at_utc");

                    b.Property<bool>("MarketingConsentGiven")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("marketing_consent_given");

                    b.Property<int?>("MaxSubAccounts")
                        .HasColumnType("integer")
                        .HasColumnName("max_sub_accounts");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("ProfileImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("profile_image_url");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_name");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("user_type");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_users_created_by_user_id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_users_is_deleted");

                    b.HasIndex("LastActivityAtUtc")
                        .HasDatabaseName("ix_users_last_activity_at_utc");

                    b.HasIndex("PhoneNumber")
                        .HasDatabaseName("ix_users_phone_number");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_users_status");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasDatabaseName("ix_users_user_name");

                    b.HasIndex("UserType")
                        .HasDatabaseName("ix_users_user_type");

                    b.HasIndex("CreatedByUserId", "IsDeleted")
                        .HasDatabaseName("ix_users_created_by_user_id_is_deleted");

                    b.HasIndex("CreatedByUserId", "UserType")
                        .HasDatabaseName("ix_users_created_by_user_id_user_type");

                    b.HasIndex("Email", "Status")
                        .HasDatabaseName("ix_users_email_status");

                    b.HasIndex("LastActivityAtUtc", "Status")
                        .HasDatabaseName("ix_users_last_activity_at_utc_status");

                    b.HasIndex("UserType", "Status")
                        .HasDatabaseName("ix_users_user_type_status");

                    b.ToTable("users", "identity");
                });

            modelBuilder.Entity("ModulusSample.Modules.Identity.Domain.Entities.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccessTokenJti")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("access_token_jti");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DeviceInfo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("device_info");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("IdTokenHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("id_token_hash");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_revoked");

                    b.Property<string>("KeycloakSessionState")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("keycloak_session_state");

                    b.Property<DateTime>("LastActivityTimeUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_activity_time_utc");

                    b.Property<DateTime>("LoginTimeUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("login_time_utc");

                    b.Property<string>("RefreshTokenJti")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("refresh_token_jti");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.Property<string>("RevokedReason")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("revoked_reason");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_user_sessions");

                    b.HasIndex("ExpiresAtUtc")
                        .HasDatabaseName("ix_user_sessions_expires_at");

                    b.HasIndex("IsRevoked")
                        .HasDatabaseName("ix_user_sessions_is_revoked");

                    b.HasIndex("KeycloakSessionState")
                        .IsUnique()
                        .HasDatabaseName("ix_user_sessions_unique_keycloak_state")
                        .HasFilter("is_revoked = FALSE");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_sessions_user_id");

                    b.HasIndex("UserId", "IsRevoked")
                        .HasDatabaseName("ix_user_sessions_user_active")
                        .HasFilter("is_revoked = FALSE");

                    b.ToTable("user_sessions", "identity");
                });

            modelBuilder.Entity("ModulusSample.Shared.Infrastructure.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_inbox_messages");

                    b.HasIndex("OccurredOnUtc")
                        .HasDatabaseName("ix_inbox_messages_occurred_on_utc_pending")
                        .HasFilter("processed_on_utc IS NULL");

                    b.HasIndex("ProcessedOnUtc")
                        .HasDatabaseName("ix_inbox_messages_processed_on_utc_completed")
                        .HasFilter("processed_on_utc IS NOT NULL");

                    b.HasIndex("Type", "OccurredOnUtc")
                        .HasDatabaseName("ix_inbox_messages_type_occurred_on_utc");

                    b.ToTable("inbox_messages", "identity");
                });

            modelBuilder.Entity("ModulusSample.Shared.Infrastructure.Inbox.InboxMessageConsumer", b =>
                {
                    b.Property<Guid>("InboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("inbox_message_id");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.HasKey("InboxMessageId", "Name")
                        .HasName("pk_inbox_message_consumers");

                    b.ToTable("inbox_message_consumers", "identity");
                });

            modelBuilder.Entity("ModulusSample.Shared.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("OccurredOnUtc")
                        .HasDatabaseName("ix_outbox_messages_occurred_on_utc")
                        .HasFilter("processed_on_utc IS NULL");

                    b.HasIndex("ProcessedOnUtc")
                        .HasDatabaseName("ix_outbox_messages_processed_on_utc")
                        .HasFilter("processed_on_utc IS NOT NULL");

                    b.ToTable("outbox_messages", "identity");
                });

            modelBuilder.Entity("ModulusSample.Shared.Infrastructure.Outbox.OutboxMessageConsumer", b =>
                {
                    b.Property<Guid>("OutboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("outbox_message_id");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.HasKey("OutboxMessageId", "Name")
                        .HasName("pk_outbox_message_consumers");

                    b.ToTable("outbox_message_consumers", "identity");
                });

            modelBuilder.Entity("ModulusSample.Modules.Identity.Domain.Entities.EmailVerificationToken", b =>
                {
                    b.HasOne("ModulusSample.Modules.Identity.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_email_verification_tokens_users");
                });

            modelBuilder.Entity("ModulusSample.Modules.Identity.Domain.Entities.ExternalLogin", b =>
                {
                    b.HasOne("ModulusSample.Modules.Identity.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_external_logins_users_user_id");
                });

            modelBuilder.Entity("ModulusSample.Modules.Identity.Domain.Entities.Role", b =>
                {
                    b.OwnsMany("ModulusSample.Modules.Identity.Domain.Entities.RolePermission", "_permissions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("GrantedAtUtc")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("granted_at_utc")
                                .HasDefaultValueSql("(NOW() AT TIME ZONE 'UTC')");

                            b1.Property<Guid>("GrantedByUserId")
                                .HasColumnType("uuid")
                                .HasColumnName("granted_by_user_id");

                            b1.Property<bool>("IsActive")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(true)
                                .HasColumnName("is_active");

                            b1.Property<string>("PermissionId")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("permission_id");

                            b1.Property<DateTime?>("RevokedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("revoked_at_utc");

                            b1.Property<Guid?>("RevokedByUserId")
                                .HasColumnType("uuid")
                                .HasColumnName("revoked_by_user_id");

                            b1.Property<Guid>("RoleId")
                                .HasColumnType("uuid")
                                .HasColumnName("role_id");

                            b1.HasKey("Id")
                                .HasName("pk_role_permissions");

                            b1.HasIndex("GrantedByUserId")
                                .HasDatabaseName("ix_role_permissions_granted_by_user_id");

                            b1.HasIndex("IsActive")
                                .HasDatabaseName("ix_role_permissions_is_active");

                            b1.HasIndex("PermissionId")
                                .HasDatabaseName("ix_role_permissions_permission_id");

                            b1.HasIndex("RoleId")
                                .HasDatabaseName("ix_role_permissions_role_id");

                            b1.HasIndex("RoleId", "IsActive")
                                .HasDatabaseName("ix_role_permissions_role_id_is_active");

                            b1.HasIndex("RoleId", "PermissionId")
                                .HasDatabaseName("ix_role_permissions_role_id_permission_id");

                            b1.ToTable("role_permissions", "identity");

                            b1.WithOwner()
                                .HasForeignKey("RoleId")
                                .HasConstraintName("fk_role_permissions_roles_role_id");
                        });

                    b.Navigation("_permissions");
                });

            modelBuilder.Entity("ModulusSample.Modules.Identity.Domain.Entities.User", b =>
                {
                    b.OwnsMany("ModulusSample.Modules.Identity.Domain.Entities.UserAddress", "_addresses", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("CreatedAtUtc")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at_utc")
                                .HasDefaultValueSql("(NOW() AT TIME ZONE 'UTC')");

                            b1.Property<bool>("IsPrimary")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("is_primary");

                            b1.Property<string>("Label")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("label");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid")
                                .HasColumnName("user_id");

                            b1.HasKey("Id")
                                .HasName("pk_user_addresses");

                            b1.HasIndex("IsPrimary")
                                .HasDatabaseName("ix_user_addresses_is_primary");

                            b1.HasIndex("UserId")
                                .HasDatabaseName("ix_user_addresses_user_id");

                            b1.HasIndex("UserId", "CreatedAtUtc")
                                .HasDatabaseName("ix_user_addresses_user_id_created_at_utc");

                            b1.HasIndex("UserId", "IsPrimary")
                                .HasDatabaseName("ix_user_addresses_user_id_is_primary");

                            b1.ToTable("user_addresses", "identity");

                            b1.WithOwner()
                                .HasForeignKey("UserId")
                                .HasConstraintName("fk_user_addresses_users_user_id");

                            b1.OwnsOne("ModulusSample.Shared.Domain.ValueObjects.Address", "Address", b2 =>
                                {
                                    b2.Property<Guid>("UserAddressId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<string>("AddressLine1")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("character varying(200)")
                                        .HasColumnName("address_line1");

                                    b2.Property<string>("AddressLine2")
                                        .HasMaxLength(200)
                                        .HasColumnType("character varying(200)")
                                        .HasColumnName("address_line2");

                                    b2.Property<string>("City")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)")
                                        .HasColumnName("city");

                                    b2.Property<string>("Country")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("country");

                                    b2.Property<string>("County")
                                        .HasColumnType("text")
                                        .HasColumnName("address_county");

                                    b2.Property<double?>("Latitude")
                                        .HasPrecision(9, 6)
                                        .HasColumnType("double precision")
                                        .HasColumnName("latitude");

                                    b2.Property<double?>("Longitude")
                                        .HasPrecision(9, 6)
                                        .HasColumnType("double precision")
                                        .HasColumnName("longitude");

                                    b2.Property<string>("Notes")
                                        .HasMaxLength(500)
                                        .HasColumnType("character varying(500)")
                                        .HasColumnName("notes");

                                    b2.Property<string>("Postcode")
                                        .IsRequired()
                                        .HasMaxLength(10)
                                        .HasColumnType("character varying(10)")
                                        .HasColumnName("postcode");

                                    b2.HasKey("UserAddressId");

                                    b2.HasIndex("Postcode")
                                        .HasDatabaseName("ix_address_postcode");

                                    b2.ToTable("user_addresses", "identity");

                                    b2.WithOwner()
                                        .HasForeignKey("UserAddressId")
                                        .HasConstraintName("fk_user_addresses_user_addresses_id");
                                });

                            b1.Navigation("Address")
                                .IsRequired();
                        });

                    b.OwnsMany("ModulusSample.Modules.Identity.Domain.Entities.UserConsent", "_consents", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("ConsentType")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("consent_type");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("description");

                            b1.Property<string>("DeviceId")
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("device_id");

                            b1.Property<string>("FingerprintHash")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("fingerprint_hash");

                            b1.Property<DateTime?>("GivenAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("given_at_utc");

                            b1.Property<string>("IpAddress")
                                .HasMaxLength(45)
                                .HasColumnType("character varying(45)")
                                .HasColumnName("ip_address");

                            b1.Property<bool>("IsGiven")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("is_given");

                            b1.Property<int>("PolicyVersion")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasDefaultValue(1)
                                .HasColumnName("policy_version");

                            b1.Property<DateTime?>("RevokedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("revoked_at_utc");

                            b1.Property<string>("UserAgent")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("user_agent");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid")
                                .HasColumnName("user_id");

                            b1.Property<int>("Version")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasDefaultValue(1)
                                .HasColumnName("version");

                            b1.HasKey("Id")
                                .HasName("pk_user_consents");

                            b1.HasIndex("ConsentType")
                                .HasDatabaseName("ix_user_consents_consent_type");

                            b1.HasIndex("GivenAtUtc")
                                .HasDatabaseName("ix_user_consents_given_at_utc");

                            b1.HasIndex("IsGiven")
                                .HasDatabaseName("ix_user_consents_is_given");

                            b1.HasIndex("RevokedAtUtc")
                                .HasDatabaseName("ix_user_consents_revoked_at_utc");

                            b1.HasIndex("UserId")
                                .HasDatabaseName("ix_user_consents_user_id");

                            b1.HasIndex("UserId", "ConsentType")
                                .HasDatabaseName("ix_user_consents_user_id_consent_type");

                            b1.HasIndex("UserId", "IsGiven")
                                .HasDatabaseName("ix_user_consents_user_id_is_given");

                            b1.HasIndex("UserId", "ConsentType", "Version")
                                .HasDatabaseName("ix_user_consents_user_id_consent_type_version");

                            b1.ToTable("user_consents", "identity");

                            b1.WithOwner()
                                .HasForeignKey("UserId")
                                .HasConstraintName("fk_user_consents_users_user_id");
                        });

                    b.OwnsMany("ModulusSample.Modules.Identity.Domain.Entities.UserRole", "_userRoles", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("AssignedAtUtc")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("assigned_at_utc")
                                .HasDefaultValueSql("(NOW() AT TIME ZONE 'UTC')");

                            b1.Property<Guid>("RoleId")
                                .HasColumnType("uuid")
                                .HasColumnName("role_id");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid")
                                .HasColumnName("user_id");

                            b1.HasKey("Id")
                                .HasName("pk_user_roles");

                            b1.HasIndex("AssignedAtUtc")
                                .HasDatabaseName("ix_user_roles_assigned_at_utc");

                            b1.HasIndex("RoleId")
                                .HasDatabaseName("ix_user_roles_role_id");

                            b1.HasIndex("UserId")
                                .HasDatabaseName("ix_user_roles_user_id");

                            b1.HasIndex("UserId", "RoleId")
                                .IsUnique()
                                .HasDatabaseName("ix_user_roles_user_id_role_id");

                            b1.ToTable("user_roles", "identity");

                            b1.WithOwner()
                                .HasForeignKey("UserId")
                                .HasConstraintName("fk_user_roles_users_user_id");
                        });

                    b.Navigation("_addresses");

                    b.Navigation("_consents");

                    b.Navigation("_userRoles");
                });

            modelBuilder.Entity("ModulusSample.Modules.Identity.Domain.Entities.UserSession", b =>
                {
                    b.HasOne("ModulusSample.Modules.Identity.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_sessions_users_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
