<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Modulus.Events/Modulus.Events.csproj" />
    <ProjectReference Include="../../data/Modulus.EntityFrameworkCore/Modulus.EntityFrameworkCore.csproj" />
    <PackageReference Include="Polly" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Modulus.Inbox.Tests" />
  </ItemGroup>

</Project>
