// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TradeFlow.Modules.Procurement.Infrastructure.Database;

#nullable disable

namespace TradeFlow.Modules.Procurement.Infrastructure.Migrations
{
    [DbContext(typeof(ProcurementDbContext))]
    partial class ProcurementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("procurement")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Modulus.Outbox.Abstractions.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CausationId")
                        .HasColumnType("text")
                        .HasColumnName("causation_id");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("text")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("LockedBy")
                        .HasColumnType("text")
                        .HasColumnName("locked_by");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("message_type");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("module_name");

                    b.Property<DateTime?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_outbox_messages_tenant_id");

                    b.HasIndex("ProcessedAt", "CreatedAt")
                        .HasDatabaseName("ix_outbox_messages_processed_at_created_at");

                    b.HasIndex("ProcessedAt", "LockedUntil", "RetryCount")
                        .HasDatabaseName("ix_outbox_messages_processed_at_locked_until_retry_count");

                    b.ToTable("outbox_messages", "procurement");
                });

            modelBuilder.Entity("TradeFlow.Modules.Procurement.Domain.Entities.PurchaseOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CfoOverrideBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cfo_override_by");

                    b.Property<string>("CfoOverrideReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cfo_override_reason");

                    b.Property<string>("CloseReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("close_reason");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("Incoterm")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("incoterm");

                    b.Property<DateOnly?>("LatestShipmentDate")
                        .HasColumnType("date")
                        .HasColumnName("latest_shipment_date");

                    b.Property<bool>("PartialShipmentAllowed")
                        .HasColumnType("boolean")
                        .HasColumnName("partial_shipment_allowed");

                    b.Property<int>("PaymentMode")
                        .HasColumnType("integer")
                        .HasColumnName("payment_mode");

                    b.Property<string>("PoNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("po_number");

                    b.Property<string>("PortOfDischarge")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("port_of_discharge");

                    b.Property<string>("PortOfLoading")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("port_of_loading");

                    b.Property<bool>("PsiRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("psi_required");

                    b.Property<decimal>("ReceivedTolerancePct")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("received_tolerance_pct");

                    b.Property<int>("RevisionVersion")
                        .HasColumnType("integer")
                        .HasColumnName("revision_version");

                    b.Property<decimal>("ShipmentTolerancePct")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("shipment_tolerance_pct");

                    b.Property<int>("Source")
                        .HasColumnType("integer")
                        .HasColumnName("source");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<bool>("TransshipmentAllowed")
                        .HasColumnType("boolean")
                        .HasColumnName("transshipment_allowed");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid")
                        .HasColumnName("vendor_id");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_purchase_orders");

                    b.HasIndex("TenantId", "PoNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_purchase_orders_tenant_id_po_number");

                    b.ToTable("purchase_orders", "procurement");
                });

            modelBuilder.Entity("TradeFlow.Modules.Procurement.Domain.Entities.PurchaseRequisition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cancellation_reason");

                    b.Property<int?>("CategoryLeadTimeDays")
                        .HasColumnType("integer")
                        .HasColumnName("category_lead_time_days");

                    b.Property<DateOnly>("CreatedOn")
                        .HasColumnType("date")
                        .HasColumnName("created_on");

                    b.Property<string>("PrNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("pr_number");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("rejection_reason");

                    b.Property<string>("RequesterName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("requester_name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_purchase_requisitions");

                    b.HasIndex("TenantId", "PrNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_purchase_requisitions_tenant_id_pr_number");

                    b.ToTable("purchase_requisitions", "procurement");
                });

            modelBuilder.Entity("TradeFlow.Modules.Procurement.Domain.Entities.Rfq", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cancellation_reason");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<DateTime>("DeadlineUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deadline_utc");

                    b.Property<bool>("IsSealed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_sealed");

                    b.Property<int>("MinBidders")
                        .HasColumnType("integer")
                        .HasColumnName("min_bidders");

                    b.Property<string>("RfqNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("rfq_number");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_rfqs");

                    b.HasIndex("TenantId", "RfqNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_rfqs_tenant_id_rfq_number");

                    b.ToTable("rfqs", "procurement");
                });

            modelBuilder.Entity("TradeFlow.Modules.Procurement.Domain.Entities.PurchaseOrder", b =>
                {
                    b.OwnsMany("TradeFlow.Modules.Procurement.Domain.Entities.PoLine", "Lines", b1 =>
                        {
                            b1.Property<Guid>("PoId")
                                .HasColumnType("uuid")
                                .HasColumnName("po_id");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("FreeText")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("free_text");

                            b1.Property<string>("HsCode")
                                .HasMaxLength(12)
                                .HasColumnType("character varying(12)")
                                .HasColumnName("hs_code");

                            b1.Property<Guid?>("ItemId")
                                .HasColumnType("uuid")
                                .HasColumnName("item_id");

                            b1.Property<string>("Notes")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("notes");

                            b1.Property<decimal>("Quantity")
                                .HasColumnType("numeric")
                                .HasColumnName("quantity");

                            b1.Property<decimal>("ReceivedQuantity")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("received_quantity");

                            b1.Property<decimal>("UnitPrice")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("unit_price");

                            b1.Property<string>("Uom")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("uom");

                            b1.HasKey("PoId", "Id")
                                .HasName("pk_po_lines");

                            b1.ToTable("po_lines", "procurement");

                            b1.WithOwner()
                                .HasForeignKey("PoId")
                                .HasConstraintName("fk_po_lines_purchase_orders_po_id");
                        });

                    b.OwnsMany("TradeFlow.Modules.Procurement.Domain.Entities.PoRevision", "Revisions", b1 =>
                        {
                            b1.Property<Guid>("PoId")
                                .HasColumnType("uuid")
                                .HasColumnName("po_id");

                            b1.Property<int>("Version")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("version");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Version"));

                            b1.Property<DateTime>("AtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("at_utc");

                            b1.Property<string>("By")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("by");

                            b1.Property<string>("Reason")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("reason");

                            b1.Property<decimal>("TotalDelta")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("total_delta");

                            b1.HasKey("PoId", "Version")
                                .HasName("pk_po_revisions");

                            b1.ToTable("po_revisions", "procurement");

                            b1.WithOwner()
                                .HasForeignKey("PoId")
                                .HasConstraintName("fk_po_revisions_purchase_orders_po_id");
                        });

                    b.OwnsOne("TradeFlow.Modules.Procurement.Domain.Entities.FeasibilitySnapshot", "Feasibility", b1 =>
                        {
                            b1.Property<Guid>("PurchaseOrderId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("EvaluatedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("evaluated_at_utc");

                            b1.PrimitiveCollection<string[]>("Reasons")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("text[]")
                                .HasColumnName("reasons");

                            b1.Property<decimal>("Score")
                                .HasPrecision(9, 6)
                                .HasColumnType("numeric(9,6)")
                                .HasColumnName("score");

                            b1.Property<string>("Verdict")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("verdict");

                            b1.HasKey("PurchaseOrderId")
                                .HasName("pk_po_feasibility");

                            b1.ToTable("po_feasibility", "procurement");

                            b1.WithOwner()
                                .HasForeignKey("PurchaseOrderId")
                                .HasConstraintName("fk_po_feasibility_purchase_orders_id");
                        });

                    b.Navigation("Feasibility");

                    b.Navigation("Lines");

                    b.Navigation("Revisions");
                });

            modelBuilder.Entity("TradeFlow.Modules.Procurement.Domain.Entities.PurchaseRequisition", b =>
                {
                    b.OwnsMany("TradeFlow.Modules.Procurement.Domain.Entities.PrLine", "Lines", b1 =>
                        {
                            b1.Property<Guid>("PrId")
                                .HasColumnType("uuid")
                                .HasColumnName("pr_id");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Category")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("category");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("currency");

                            b1.Property<decimal>("EstimatedUnitPrice")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("estimated_unit_price");

                            b1.Property<string>("FreeText")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("free_text");

                            b1.Property<Guid?>("ItemId")
                                .HasColumnType("uuid")
                                .HasColumnName("item_id");

                            b1.Property<DateOnly>("NeedByDate")
                                .HasColumnType("date")
                                .HasColumnName("need_by_date");

                            b1.Property<bool>("NeedByWarning")
                                .HasColumnType("boolean")
                                .HasColumnName("need_by_warning");

                            b1.Property<string>("Notes")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("notes");

                            b1.Property<decimal>("Quantity")
                                .HasColumnType("numeric")
                                .HasColumnName("quantity");

                            b1.Property<Guid?>("SuggestedVendorId")
                                .HasColumnType("uuid")
                                .HasColumnName("suggested_vendor_id");

                            b1.Property<string>("Uom")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("uom");

                            b1.HasKey("PrId", "Id")
                                .HasName("pk_pr_lines");

                            b1.ToTable("pr_lines", "procurement");

                            b1.WithOwner()
                                .HasForeignKey("PrId")
                                .HasConstraintName("fk_pr_lines_purchase_requisitions_pr_id");
                        });

                    b.Navigation("Lines");
                });

            modelBuilder.Entity("TradeFlow.Modules.Procurement.Domain.Entities.Rfq", b =>
                {
                    b.OwnsOne("TradeFlow.Modules.Procurement.Domain.Entities.RfqAward", "Award", b1 =>
                        {
                            b1.Property<Guid>("RfqId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("AmountFcy")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("amount_fcy");

                            b1.Property<string>("AwardedBy")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("awarded_by");

                            b1.Property<bool>("CfoApproved")
                                .HasColumnType("boolean")
                                .HasColumnName("cfo_approved");

                            b1.Property<string>("CfoApprovedBy")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("cfo_approved_by");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("currency");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Justification")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("justification");

                            b1.Property<bool>("RequiresCfoApproval")
                                .HasColumnType("boolean")
                                .HasColumnName("requires_cfo_approval");

                            b1.Property<decimal>("SplitPercent")
                                .HasPrecision(9, 6)
                                .HasColumnType("numeric(9,6)")
                                .HasColumnName("split_percent");

                            b1.Property<Guid>("VendorId")
                                .HasColumnType("uuid")
                                .HasColumnName("vendor_id");

                            b1.HasKey("RfqId")
                                .HasName("pk_rfq_awards");

                            b1.ToTable("rfq_awards", "procurement", t =>
                                {
                                    t.Property("Id")
                                        .HasColumnName("id1");
                                });

                            b1.WithOwner()
                                .HasForeignKey("RfqId")
                                .HasConstraintName("fk_rfq_awards_rfqs_id");
                        });

                    b.OwnsMany("TradeFlow.Modules.Procurement.Domain.Entities.RfqBid", "Bids", b1 =>
                        {
                            b1.Property<Guid>("RfqId")
                                .HasColumnType("uuid")
                                .HasColumnName("rfq_id");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("BidNo")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("bid_no");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("currency");

                            b1.Property<bool>("IsLate")
                                .HasColumnType("boolean")
                                .HasColumnName("is_late");

                            b1.Property<string>("Notes")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("notes");

                            b1.Property<DateTime>("SubmittedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("submitted_at_utc");

                            b1.Property<decimal>("TotalAmountFcy")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("total_amount_fcy");

                            b1.Property<Guid>("VendorId")
                                .HasColumnType("uuid")
                                .HasColumnName("vendor_id");

                            b1.HasKey("RfqId", "Id")
                                .HasName("pk_rfq_bids");

                            b1.ToTable("rfq_bids", "procurement");

                            b1.WithOwner()
                                .HasForeignKey("RfqId")
                                .HasConstraintName("fk_rfq_bids_rfqs_rfq_id");
                        });

                    b.OwnsMany("TradeFlow.Modules.Procurement.Domain.Entities.RfqComparisonRow", "Comparison", b1 =>
                        {
                            b1.Property<Guid>("RfqId")
                                .HasColumnType("uuid")
                                .HasColumnName("rfq_id");

                            b1.Property<Guid>("BidId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("bid_id");

                            b1.Property<decimal>("BidAmountFcy")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("bid_amount_fcy");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("currency");

                            b1.Property<decimal>("DutyBdt")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("duty_bdt");

                            b1.Property<decimal>("FreightBdt")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("freight_bdt");

                            b1.Property<decimal>("HandlingBdt")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("handling_bdt");

                            b1.Property<decimal>("LandedTotalBdt")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("landed_total_bdt");

                            b1.Property<Guid>("VendorId")
                                .HasColumnType("uuid")
                                .HasColumnName("vendor_id");

                            b1.HasKey("RfqId", "BidId")
                                .HasName("pk_rfq_comparison");

                            b1.ToTable("rfq_comparison", "procurement");

                            b1.WithOwner()
                                .HasForeignKey("RfqId")
                                .HasConstraintName("fk_rfq_comparison_rfqs_rfq_id");
                        });

                    b.OwnsMany("TradeFlow.Modules.Procurement.Domain.Entities.RfqInvitation", "Invitations", b1 =>
                        {
                            b1.Property<Guid>("RfqId")
                                .HasColumnType("uuid")
                                .HasColumnName("rfq_id");

                            b1.Property<Guid>("VendorId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("vendor_id");

                            b1.Property<DateTime>("InvitedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("invited_at_utc");

                            b1.HasKey("RfqId", "VendorId")
                                .HasName("pk_rfq_invitations");

                            b1.ToTable("rfq_invitations", "procurement");

                            b1.WithOwner()
                                .HasForeignKey("RfqId")
                                .HasConstraintName("fk_rfq_invitations_rfqs_rfq_id");
                        });

                    b.OwnsMany("TradeFlow.Modules.Procurement.Domain.Entities.RfqLine", "Lines", b1 =>
                        {
                            b1.Property<Guid>("RfqId")
                                .HasColumnType("uuid")
                                .HasColumnName("rfq_id");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("FreeText")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("free_text");

                            b1.Property<string>("HsCode")
                                .HasMaxLength(12)
                                .HasColumnType("character varying(12)")
                                .HasColumnName("hs_code");

                            b1.Property<Guid?>("ItemId")
                                .HasColumnType("uuid")
                                .HasColumnName("item_id");

                            b1.Property<string>("PortOfDischarge")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("port_of_discharge");

                            b1.Property<string>("PortOfLoading")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("port_of_loading");

                            b1.Property<Guid?>("PrLineId")
                                .HasColumnType("uuid")
                                .HasColumnName("pr_line_id");

                            b1.Property<decimal>("Quantity")
                                .HasColumnType("numeric")
                                .HasColumnName("quantity");

                            b1.Property<string>("Uom")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("uom");

                            b1.HasKey("RfqId", "Id")
                                .HasName("pk_rfq_lines");

                            b1.ToTable("rfq_lines", "procurement");

                            b1.WithOwner()
                                .HasForeignKey("RfqId")
                                .HasConstraintName("fk_rfq_lines_rfqs_rfq_id");
                        });

                    b.Navigation("Award");

                    b.Navigation("Bids");

                    b.Navigation("Comparison");

                    b.Navigation("Invitations");

                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
