<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Modulus.Core" Version="1.0.0" />
    <PackageReference Include="Modulus.AspNetCore" Version="1.0.0" />
    <PackageReference Include="Modulus.Mediator" Version="1.0.0" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../modulus.Modules.Catalog.Application/modulus.Modules.Catalog.Application.csproj" />
    <ProjectReference Include="../modulus.Modules.Catalog.Contracts/modulus.Modules.Catalog.Contracts.csproj" />
    <ProjectReference Include="../../modulus.Shared/modulus.Shared.Presentation/modulus.Shared.Presentation.csproj" />
  </ItemGroup>

</Project>
