<Project Sdk="Microsoft.NET.Sdk">


  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="../../../src/platform/Modulus.SignalR.Backplane/Modulus.SignalR.Backplane.csproj" />
    <PackageReference Include="Microsoft.Extensions.Configuration" />
  </ItemGroup>

</Project>
