<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../core/Modulus.Core.Abstractions/Modulus.Core.Abstractions.csproj" />
    <ProjectReference Include="../../core/Modulus.Core/Modulus.Core.csproj" />
    <PackageReference Include="BenchmarkDotNet" />
  </ItemGroup>

</Project>
