<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Cobytelabs.Modulus.Core" Version="1.2.0" />
    <PackageReference Include="Cobytelabs.Modulus.Mediator" Version="1.2.0" />
    <ProjectReference Include="../ProcureFlow.Shared.Domain/ProcureFlow.Shared.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
  </ItemGroup>

</Project>