<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Cobytelabs.Modulus.Core" Version="1.2.0" />
    <PackageReference Include="Cobytelabs.Modulus.EntityFrameworkCore" Version="1.2.0" />
    <PackageReference Include="Cobytelabs.Modulus.Data.PostgreSQL" Version="1.2.0" />
    <PackageReference Include="Cobytelabs.Modulus.Platform" Version="1.2.0" />
    <PackageReference Include="Cobytelabs.Modulus.Events" Version="1.2.0" />
    <PackageReference Include="Cobytelabs.Modulus.Mediator" Version="1.2.0" />
    <PackageReference Include="Cobytelabs.Modulus.Outbox" Version="1.2.0" />
    <PackageReference Include="Cobytelabs.Modulus.Inbox" Version="1.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Shared\ModulusSample.Shared.Infrastructure\ModulusSample.Shared.Infrastructure.csproj" />
    <ProjectReference Include="..\ModulusSample.Modules.Partners.Application\ModulusSample.Modules.Partners.Application.csproj" />
  </ItemGroup>

</Project>
