// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProcureFlow.Modules.Vendors.Infrastructure.Database;

#nullable disable

namespace ProcureFlow.Modules.Vendors.Infrastructure.Migrations
{
    [DbContext(typeof(VendorsDbContext))]
    partial class VendorsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("vendors")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Modulus.Outbox.Abstractions.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CausationId")
                        .HasColumnType("text")
                        .HasColumnName("causation_id");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("text")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("LockedBy")
                        .HasColumnType("text")
                        .HasColumnName("locked_by");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("message_type");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("module_name");

                    b.Property<DateTime?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_outbox_messages_tenant_id");

                    b.HasIndex("ProcessedAt", "CreatedAt")
                        .HasDatabaseName("ix_outbox_messages_processed_at_created_at");

                    b.HasIndex("ProcessedAt", "LockedUntil", "RetryCount")
                        .HasDatabaseName("ix_outbox_messages_processed_at_locked_until_retry_count");

                    b.ToTable("outbox_messages", "vendors");
                });

            modelBuilder.Entity("ProcureFlow.Modules.Vendors.Domain.Entities.Vendor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("Bin")
                        .HasColumnType("text")
                        .HasColumnName("bin");

                    b.Property<string>("BlacklistReason")
                        .HasColumnType("text")
                        .HasColumnName("blacklist_reason");

                    b.Property<DateTime?>("BlacklistedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("blacklisted_at_utc");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("legal_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Tin")
                        .HasColumnType("text")
                        .HasColumnName("tin");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<int>("VendorType")
                        .HasColumnType("integer")
                        .HasColumnName("vendor_type");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_vendors");

                    b.ToTable("vendors", "vendors");
                });

            modelBuilder.Entity("ProcureFlow.Modules.Vendors.Domain.Entities.Vendor", b =>
                {
                    b.OwnsMany("ProcureFlow.Modules.Vendors.Domain.Entities.VendorBankAccount", "BankAccounts", b1 =>
                        {
                            b1.Property<Guid>("VendorId")
                                .HasColumnType("uuid")
                                .HasColumnName("vendor_id");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("AccountName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("account_name");

                            b1.Property<string>("AccountNumber")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("account_number");

                            b1.Property<string>("BankName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("bank_name");

                            b1.Property<string>("Branch")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("branch");

                            b1.Property<DateTime?>("CheckedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("checked_at_utc");

                            b1.Property<string>("CheckerUserId")
                                .HasColumnType("text")
                                .HasColumnName("checker_user_id");

                            b1.Property<DateTime>("CreatedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at_utc");

                            b1.Property<string>("MakerUserId")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("maker_user_id");

                            b1.Property<string>("RejectionReason")
                                .HasColumnType("text")
                                .HasColumnName("rejection_reason");

                            b1.Property<int>("Status")
                                .HasColumnType("integer")
                                .HasColumnName("status");

                            b1.Property<string>("SwiftCode")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("swift_code");

                            b1.HasKey("VendorId", "Id")
                                .HasName("pk_vendor_bank_accounts");

                            b1.ToTable("vendor_bank_accounts", "vendors");

                            b1.WithOwner()
                                .HasForeignKey("VendorId")
                                .HasConstraintName("fk_vendor_bank_accounts_vendors_vendor_id");
                        });

                    b.OwnsMany("ProcureFlow.Modules.Vendors.Domain.Entities.VendorQualification", "Qualifications", b1 =>
                        {
                            b1.Property<Guid>("VendorId")
                                .HasColumnType("uuid")
                                .HasColumnName("vendor_id");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Category")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("category");

                            b1.Property<string>("CertificateNumber")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("certificate_number");

                            b1.Property<DateTime>("CreatedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at_utc");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("created_by");

                            b1.Property<DateOnly>("ValidFrom")
                                .HasColumnType("date")
                                .HasColumnName("valid_from");

                            b1.Property<DateOnly>("ValidTo")
                                .HasColumnType("date")
                                .HasColumnName("valid_to");

                            b1.HasKey("VendorId", "Id")
                                .HasName("pk_vendor_qualifications");

                            b1.ToTable("vendor_qualifications", "vendors");

                            b1.WithOwner()
                                .HasForeignKey("VendorId")
                                .HasConstraintName("fk_vendor_qualifications_vendors_vendor_id");
                        });

                    b.OwnsMany("ProcureFlow.Modules.Vendors.Domain.Entities.VendorScorecard", "Scorecards", b1 =>
                        {
                            b1.Property<Guid>("VendorId")
                                .HasColumnType("uuid")
                                .HasColumnName("vendor_id");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("ComplianceScore")
                                .HasColumnType("numeric")
                                .HasColumnName("compliance_score");

                            b1.Property<DateTime>("CreatedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at_utc");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("created_by");

                            b1.Property<decimal>("DeliveryScore")
                                .HasColumnType("numeric")
                                .HasColumnName("delivery_score");

                            b1.Property<decimal>("PriceScore")
                                .HasColumnType("numeric")
                                .HasColumnName("price_score");

                            b1.Property<decimal>("QualityScore")
                                .HasColumnType("numeric")
                                .HasColumnName("quality_score");

                            b1.Property<decimal>("WeightedAverage")
                                .HasColumnType("numeric")
                                .HasColumnName("weighted_average");

                            b1.HasKey("VendorId", "Id")
                                .HasName("pk_vendor_scorecards");

                            b1.ToTable("vendor_scorecards", "vendors");

                            b1.WithOwner()
                                .HasForeignKey("VendorId")
                                .HasConstraintName("fk_vendor_scorecards_vendors_vendor_id");
                        });

                    b.Navigation("BankAccounts");

                    b.Navigation("Qualifications");

                    b.Navigation("Scorecards");
                });
#pragma warning restore 612, 618
        }
    }
}
